/**
 * SUB_INVOICES_ARC Phase 1 — Supabase helpers for sub invoice AP workflow.
 *
 * All helpers:
 *  - Return { ok, error, data } — never throw
 *  - Are tenant-scoped via RLS (no explicit tenant_id param needed)
 *  - Await all state-change operations and return the real DB result
 *
 * Status is DERIVED via compute_sub_invoice_status() — not stored on the row.
 * Phase 4 (cash accounting) will wire sbAddSubInvoicePayment to also write
 * a job_transactions row. The transaction_id FK exists on sub_invoice_payments
 * now; it will be populated then.
 */

import { sb, AV_USER_ID } from './supabase.js';

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Create a sub invoice (shared by PDF upload and manual entry paths).
 *
 * If invoiceNumber is omitted, auto-generates in format:
 *   <sub-name-slug>-<job-id-last-6>-<seq>
 * and sets auto_generated_number=true.
 *
 * @param {object} params
 * @param {string}  params.jobId
 * @param {string}  params.subContactId              contacts.id (TEXT)
 * @param {string}  [params.invoiceNumber]            omit to auto-generate
 * @param {string}  params.invoiceDate               YYYY-MM-DD
 * @param {string}  [params.dueDate]                 YYYY-MM-DD
 * @param {number}  params.amount
 * @param {string}  [params.description]
 * @param {Array}   [params.lineItems]               [{description,qty?,unitPrice?,total}]
 * @param {string}  [params.relatedScheduleItemId]
 * @param {string}  [params.invoiceFileId]           job_files.id
 * @param {'manual_upload'|'pdf_upload'|'master_agent'|'sub_portal'} params.submittedVia
 * @returns {Promise<{ok:boolean, error?:string, data?:{invoiceId:string, invoiceNumber:string, autoGenerated:boolean}}>}
 */
export async function sbCreateSubInvoice({
  jobId,
  subContactId,
  invoiceNumber,
  invoiceDate,
  dueDate,
  amount,
  description,
  lineItems,
  relatedScheduleItemId,
  invoiceFileId,
  submittedVia = 'manual_upload',
}) {
  try {
    let finalNumber = invoiceNumber;
    let autoGenerated = false;

    if (!finalNumber) {
      // Fetch sub name for slug
      const { data: contact } = await sb
        .from('contacts')
        .select('name')
        .eq('id', subContactId)
        .maybeSingle();
      const rawName = contact?.name || 'sub';
      const nameSlug = rawName
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 20);
      const jobShort = String(jobId).slice(-6);
      // Count existing invoices for this sub+job to determine seq
      const { count } = await sb
        .from('sub_invoices')
        .select('id', { count: 'exact', head: true })
        .eq('job_id', jobId)
        .eq('sub_contact_id', subContactId)
        .is('voided_at', null);
      const seq = (count || 0) + 1;
      finalNumber = `${nameSlug}-${jobShort}-${seq}`;
      autoGenerated = true;
    }

    const payload = {
      job_id:                    jobId,
      sub_contact_id:            subContactId,
      invoice_number:            finalNumber,
      auto_generated_number:     autoGenerated,
      invoice_date:              invoiceDate,
      due_date:                  dueDate || null,
      amount,
      description:               description || null,
      line_items:                lineItems || null,
      related_schedule_item_id:  relatedScheduleItemId || null,
      invoice_file_id:           invoiceFileId || null,
      submitted_via:             submittedVia,
      created_by_id:             AV_USER_ID,
    };

    const { data, error } = await sb
      .from('sub_invoices')
      .insert(payload)
      .select('id, invoice_number, auto_generated_number')
      .single();

    if (error) return { ok: false, error: error.message };
    return {
      ok: true,
      data: {
        invoiceId:    data.id,
        invoiceNumber: data.invoice_number,
        autoGenerated: data.auto_generated_number,
      },
    };
  } catch (e) {
    return { ok: false, error: e.message || 'sbCreateSubInvoice failed' };
  }
}

/**
 * Add a payment against an existing invoice.
 *
 * Rejects if invoice is disputed or voided.
 * Returns newStatus from compute_sub_invoice_status after insert.
 * Phase 4 will extend this to also write a job_transactions row.
 *
 * @param {object} params
 * @param {string}  params.subInvoiceId
 * @param {number}  params.amount
 * @param {string}  params.paidDate     YYYY-MM-DD
 * @param {'check'|'ach'|'cash'|'card'|'other'} params.method
 * @param {string}  [params.reference]
 * @param {string}  [params.notes]
 * @returns {Promise<{ok:boolean, error?:string, data?:{paymentId:string, newStatus:string}}>}
 */
export async function sbAddSubInvoicePayment({
  subInvoiceId,
  amount,
  paidDate,
  method,
  reference,
  notes,
}) {
  try {
    // Guard: fetch invoice state before inserting
    const { data: inv, error: invErr } = await sb
      .from('sub_invoices')
      .select('disputed, voided_at, approved_at')
      .eq('id', subInvoiceId)
      .single();

    if (invErr || !inv) return { ok: false, error: 'Invoice not found' };
    if (inv.voided_at)   return { ok: false, error: 'Cannot add payment to voided invoice' };
    if (inv.disputed)    return { ok: false, error: 'Cannot add payment to disputed invoice' };
    if (!inv.approved_at) return { ok: false, error: 'Invoice must be approved before recording payment' };

    const { data: payment, error: payErr } = await sb
      .from('sub_invoice_payments')
      .insert({
        sub_invoice_id: subInvoiceId,
        amount,
        paid_date:      paidDate,
        method,
        reference:      reference || null,
        notes:          notes || null,
        created_by_id:  AV_USER_ID,
      })
      .select('id')
      .single();

    if (payErr) return { ok: false, error: payErr.message };

    // Derive new status via DB function (source-of-truth)
    const { data: statusResult, error: statusErr } = await sb
      .rpc('compute_sub_invoice_status', { p_invoice_id: subInvoiceId });

    const newStatus = statusErr ? 'unknown' : (statusResult || 'unknown');

    return {
      ok: true,
      data: { paymentId: payment.id, newStatus },
    };
  } catch (e) {
    return { ok: false, error: e.message || 'sbAddSubInvoicePayment failed' };
  }
}

/**
 * Void a payment. Retains the row for audit trail; sum excludes voided rows.
 * Does NOT delete or void the linked job_transactions row in Phase 1
 * (Phase 4 will handle that side).
 *
 * @param {object} params
 * @param {string}  params.paymentId
 * @param {string}  params.voidReason
 * @returns {Promise<{ok:boolean, error?:string, data?:{newStatus:string}}>}
 */
export async function sbVoidSubInvoicePayment({ paymentId, voidReason }) {
  try {
    // Fetch the payment to get sub_invoice_id
    const { data: payment, error: fetchErr } = await sb
      .from('sub_invoice_payments')
      .select('id, sub_invoice_id, voided_at')
      .eq('id', paymentId)
      .single();

    if (fetchErr || !payment) return { ok: false, error: 'Payment not found' };
    if (payment.voided_at)    return { ok: false, error: 'Payment is already voided' };

    const { error: voidErr } = await sb
      .from('sub_invoice_payments')
      .update({
        voided_at:    new Date().toISOString(),
        voided_by_id: AV_USER_ID,
        void_reason:  voidReason || null,
      })
      .eq('id', paymentId);

    if (voidErr) return { ok: false, error: voidErr.message };

    const { data: statusResult, error: statusErr } = await sb
      .rpc('compute_sub_invoice_status', { p_invoice_id: payment.sub_invoice_id });

    const newStatus = statusErr ? 'unknown' : (statusResult || 'unknown');
    return { ok: true, data: { newStatus } };
  } catch (e) {
    return { ok: false, error: e.message || 'sbVoidSubInvoicePayment failed' };
  }
}

/**
 * Approve an invoice. Sets approved_at + approved_by_id.
 * RLS restricts UPDATE to owner/PM — role gate is enforced at the DB level.
 *
 * @param {object} params
 * @param {string}  params.subInvoiceId
 * @returns {Promise<{ok:boolean, error?:string, data?:{approvedAt:string}}>}
 */
export async function sbApproveSubInvoice({ subInvoiceId }) {
  try {
    const { data: inv, error: fetchErr } = await sb
      .from('sub_invoices')
      .select('disputed, voided_at, approved_at')
      .eq('id', subInvoiceId)
      .single();

    if (fetchErr || !inv) return { ok: false, error: 'Invoice not found' };
    if (inv.voided_at)    return { ok: false, error: 'Cannot approve a voided invoice' };
    if (inv.disputed)     return { ok: false, error: 'Resolve dispute before approving' };
    if (inv.approved_at)  return { ok: false, error: 'Invoice is already approved' };

    const now = new Date().toISOString();
    const { error: updateErr } = await sb
      .from('sub_invoices')
      .update({ approved_at: now, approved_by_id: AV_USER_ID })
      .eq('id', subInvoiceId);

    if (updateErr) return { ok: false, error: updateErr.message };
    return { ok: true, data: { approvedAt: now } };
  } catch (e) {
    return { ok: false, error: e.message || 'sbApproveSubInvoice failed' };
  }
}

/**
 * Toggle dispute state on/off.
 * disputed=true freezes payment and approval actions.
 * disputed=false (resolve) restores normal flow.
 *
 * @param {object} params
 * @param {string}   params.subInvoiceId
 * @param {boolean}  params.disputed
 * @param {string}   [params.disputeReason]  required when disputed=true
 * @returns {Promise<{ok:boolean, error?:string}>}
 */
export async function sbDisputeSubInvoice({ subInvoiceId, disputed, disputeReason }) {
  try {
    const { data: inv, error: fetchErr } = await sb
      .from('sub_invoices')
      .select('voided_at')
      .eq('id', subInvoiceId)
      .single();

    if (fetchErr || !inv) return { ok: false, error: 'Invoice not found' };
    if (inv.voided_at)    return { ok: false, error: 'Cannot dispute a voided invoice' };

    const patch = disputed
      ? {
          disputed:        true,
          disputed_at:     new Date().toISOString(),
          disputed_by_id:  AV_USER_ID,
          dispute_reason:  disputeReason || null,
        }
      : {
          disputed:        false,
          disputed_at:     null,
          disputed_by_id:  null,
          dispute_reason:  null,
        };

    const { error: updateErr } = await sb
      .from('sub_invoices')
      .update(patch)
      .eq('id', subInvoiceId);

    if (updateErr) return { ok: false, error: updateErr.message };
    return { ok: true };
  } catch (e) {
    return { ok: false, error: e.message || 'sbDisputeSubInvoice failed' };
  }
}

/**
 * Edit invoice fields.
 * If amount is provided, validates that new amount >= sum of non-voided payments.
 *
 * @param {object} params
 * @param {string}  params.subInvoiceId
 * @param {number}  [params.amount]
 * @param {string}  [params.invoiceDate]            YYYY-MM-DD
 * @param {string}  [params.dueDate]                YYYY-MM-DD or null to clear
 * @param {string}  [params.description]
 * @param {Array}   [params.lineItems]              null to clear
 * @param {string}  [params.relatedScheduleItemId]  null to clear
 * @returns {Promise<{ok:boolean, error?:string}>}
 */
export async function sbEditSubInvoice({
  subInvoiceId,
  amount,
  invoiceDate,
  dueDate,
  description,
  lineItems,
  relatedScheduleItemId,
}) {
  try {
    // If changing amount, validate against already-paid sum
    if (amount !== undefined) {
      const { data: payments } = await sb
        .from('sub_invoice_payments')
        .select('amount')
        .eq('sub_invoice_id', subInvoiceId)
        .is('voided_at', null);

      const paidSum = (payments || []).reduce((s, p) => s + Number(p.amount || 0), 0);
      if (amount < paidSum) {
        return {
          ok: false,
          error: `New amount ($${amount.toFixed(2)}) is less than already-paid sum ($${paidSum.toFixed(2)}). Void payment(s) first.`,
        };
      }
    }

    // Build patch from only the fields that were explicitly passed
    const patch = {};
    if (amount !== undefined)                   patch.amount = amount;
    if (invoiceDate !== undefined)              patch.invoice_date = invoiceDate;
    if ('dueDate' in arguments[0])             patch.due_date = dueDate ?? null;
    if ('description' in arguments[0])         patch.description = description ?? null;
    if ('lineItems' in arguments[0])           patch.line_items = lineItems ?? null;
    if ('relatedScheduleItemId' in arguments[0]) patch.related_schedule_item_id = relatedScheduleItemId ?? null;

    if (Object.keys(patch).length === 0) return { ok: true }; // nothing to update

    const { error: updateErr } = await sb
      .from('sub_invoices')
      .update(patch)
      .eq('id', subInvoiceId);

    if (updateErr) return { ok: false, error: updateErr.message };
    return { ok: true };
  } catch (e) {
    return { ok: false, error: e.message || 'sbEditSubInvoice failed' };
  }
}

/**
 * Load all invoices for a job with derived status, paid sum, balance, and payment history.
 *
 * Status is derived per-row via compute_sub_invoice_status RPC.
 * paidSum and balance are computed in JS from the payments array.
 *
 * @param {object} params
 * @param {string}  params.jobId
 * @returns {Promise<{ok:boolean, error?:string, data?:Array}>}
 */
export async function sbLoadSubInvoices({ jobId }) {
  try {
    // Load invoices with sub contact name + all payments
    const { data: invoices, error: invErr } = await sb
      .from('sub_invoices')
      .select(`
        id,
        invoice_number,
        auto_generated_number,
        sub_contact_id,
        invoice_date,
        due_date,
        amount,
        description,
        line_items,
        invoice_file_id,
        lien_waiver_file_id,
        related_schedule_item_id,
        approved_at,
        approved_by_id,
        disputed,
        dispute_reason,
        voided_at,
        submitted_via,
        created_at,
        sub_contact:contacts!sub_contact_id(name),
        payments:sub_invoice_payments(
          id,
          amount,
          paid_date,
          method,
          reference,
          notes,
          voided_at,
          void_reason,
          transaction_id
        )
      `)
      .eq('job_id', jobId)
      .order('invoice_date', { ascending: false });

    if (invErr) return { ok: false, error: invErr.message };

    // Enrich each invoice with derived status (via RPC) + computed financials
    const enriched = await Promise.all(
      (invoices || []).map(async (inv) => {
        // Compute paid sum from non-voided payments (JS — no extra RPC needed)
        const nonVoidedPayments = (inv.payments || []).filter(p => !p.voided_at);
        const paidSum = nonVoidedPayments.reduce((s, p) => s + Number(p.amount || 0), 0);
        const balance = Math.max(0, Number(inv.amount) - paidSum);

        // Call RPC for source-of-truth status (handles all edge cases in one place)
        const { data: status } = await sb
          .rpc('compute_sub_invoice_status', { p_invoice_id: inv.id });

        return {
          id:                      inv.id,
          invoiceNumber:           inv.invoice_number,
          autoGeneratedNumber:     inv.auto_generated_number,
          subContactId:            inv.sub_contact_id,
          subName:                 inv.sub_contact?.name || '—',
          invoiceDate:             inv.invoice_date,
          dueDate:                 inv.due_date,
          amount:                  Number(inv.amount),
          paidSum,
          balance,
          status:                  status || 'unknown',
          approvedAt:              inv.approved_at,
          approvedById:            inv.approved_by_id,
          disputed:                inv.disputed,
          disputeReason:           inv.dispute_reason,
          voidedAt:                inv.voided_at,
          invoiceFileId:           inv.invoice_file_id,
          lienWaiverFileId:        inv.lien_waiver_file_id,
          relatedScheduleItemId:   inv.related_schedule_item_id,
          description:             inv.description,
          lineItems:               inv.line_items,
          submittedVia:            inv.submitted_via,
          createdAt:               inv.created_at,
          payments: (inv.payments || []).map(p => ({
            id:            p.id,
            amount:        Number(p.amount),
            paidDate:      p.paid_date,
            method:        p.method,
            reference:     p.reference,
            notes:         p.notes,
            voidedAt:      p.voided_at,
            voidReason:    p.void_reason,
            transactionId: p.transaction_id,
          })),
        };
      })
    );

    return { ok: true, data: enriched };
  } catch (e) {
    return { ok: false, error: e.message || 'sbLoadSubInvoices failed' };
  }
}
