/**
 * SUB_INVOICES_ARC Phase 1–v2 — Supabase helpers for sub invoice AP workflow.
 *
 * All helpers:
 *  - Return { ok, error, data } — never throw
 *  - Are tenant-scoped via RLS (no explicit tenant_id param needed)
 *  - Await all state-change operations and return the real DB result
 *
 * Status is DERIVED via compute_sub_invoice_status() — not stored on the row.
 *
 * v2 additions:
 *  - sbCreateSubInvoiceAccrualRow: creates a pending job_transactions row when
 *    a sub invoice is approved on a cost_plus job (Float Out visibility).
 *  - sbApproveSubInvoice now calls sbCreateSubInvoiceAccrualRow after approval.
 *  - sbAddSubInvoicePayment flips the accrual row to 'paid' on full payment.
 *  - sbVoidSubInvoicePayment reverts the accrual to 'pending' if invoice is no longer paid.
 *  - sbDisputeSubInvoice cancels the accrual on dispute; restores it on resolve.
 */

import { sb, AV_TENANT, AV_USER_ID, sbSaveContact } from './supabase.js';

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Create a sub invoice (shared by PDF upload and manual entry paths).
 *
 * If invoiceNumber is omitted, auto-generates in format:
 *   <sub-name-slug>-<job-id-last-6>-<seq>
 * and sets auto_generated_number=true.
 *
 * @param {object} params
 * @param {string}  params.jobId
 * @param {string}  params.subContactId              contacts.id (TEXT)
 * @param {string}  [params.invoiceNumber]            omit to auto-generate
 * @param {string}  params.invoiceDate               YYYY-MM-DD
 * @param {string}  [params.dueDate]                 YYYY-MM-DD
 * @param {number}  params.amount
 * @param {string}  [params.description]
 * @param {Array}   [params.lineItems]               [{description,qty?,unitPrice?,total}]
 * @param {string}  [params.relatedScheduleItemId]
 * @param {string}  [params.invoiceFileId]           job_files.id
 * @param {'manual_upload'|'pdf_upload'|'master_agent'|'sub_portal'} params.submittedVia
 * @returns {Promise<{ok:boolean, error?:string, data?:{invoiceId:string, invoiceNumber:string, autoGenerated:boolean}}>}
 */
export async function sbCreateSubInvoice({
  jobId,
  subContactId,
  invoiceNumber,
  invoiceDate,
  dueDate,
  amount,
  description,
  lineItems,
  relatedScheduleItemId,
  invoiceFileId,
  submittedVia = 'manual_upload',
}) {
  try {
    let finalNumber = invoiceNumber;
    let autoGenerated = false;

    if (!finalNumber) {
      // Fetch sub name for slug
      const { data: contact } = await sb
        .from('contacts')
        .select('name')
        .eq('id', subContactId)
        .maybeSingle();
      const rawName = contact?.name || 'sub';
      const nameSlug = rawName
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 20);
      const jobShort = String(jobId).slice(-6);
      // Count existing invoices for this sub+job to determine seq
      const { count } = await sb
        .from('sub_invoices')
        .select('id', { count: 'exact', head: true })
        .eq('job_id', jobId)
        .eq('sub_contact_id', subContactId)
        .is('voided_at', null);
      const seq = (count || 0) + 1;
      finalNumber = `${nameSlug}-${jobShort}-${seq}`;
      autoGenerated = true;
    }

    const payload = {
      tenant_id:                 AV_TENANT,
      job_id:                    jobId,
      sub_contact_id:            subContactId,
      invoice_number:            finalNumber,
      auto_generated_number:     autoGenerated,
      invoice_date:              invoiceDate,
      due_date:                  dueDate || null,
      amount,
      description:               description || null,
      line_items:                lineItems || null,
      related_schedule_item_id:  relatedScheduleItemId || null,
      invoice_file_id:           invoiceFileId || null,
      submitted_via:             submittedVia,
      created_by_id:             AV_USER_ID,
    };

    const { data, error } = await sb
      .from('sub_invoices')
      .insert(payload)
      .select('id, invoice_number, auto_generated_number')
      .single();

    if (error) return { ok: false, error: error.message };
    return {
      ok: true,
      data: {
        invoiceId:    data.id,
        invoiceNumber: data.invoice_number,
        autoGenerated: data.auto_generated_number,
      },
    };
  } catch (e) {
    return { ok: false, error: e.message || 'sbCreateSubInvoice failed' };
  }
}

/**
 * Add a payment against an existing invoice — Phase 4a atomic version.
 *
 * Delegates to the add_sub_invoice_payment_with_ledger Postgres function which
 * inserts sub_invoice_payments + job_transactions in one transaction (no partial
 * commits). Guards (voided, disputed, unapproved) are enforced at the DB level.
 *
 * @param {object} params
 * @param {string}  params.subInvoiceId
 * @param {number}  params.amount
 * @param {string}  params.paidDate     YYYY-MM-DD
 * @param {'check'|'ach'|'cash'|'card'|'other'} params.method
 * @param {string}  [params.reference]
 * @param {string}  [params.notes]
 * @returns {Promise<{ok:boolean, error?:string, data?:{paymentId:string, transactionId:string, newStatus:string}}>}
 */
export async function sbAddSubInvoicePayment({
  subInvoiceId,
  amount,
  paidDate,
  method,
  reference,
  notes,
}) {
  try {
    const { data, error } = await sb.rpc('add_sub_invoice_payment_with_ledger', {
      p_sub_invoice_id: subInvoiceId,
      p_amount:         amount,
      p_paid_date:      paidDate,
      p_method:         method,
      p_reference:      reference || null,
      p_notes:          notes    || null,
    });

    if (error) return { ok: false, error: error.message };

    const row = Array.isArray(data) ? data[0] : data;
    const newStatus = row.new_status;

    // Accrual drawdown is now handled atomically inside the RPC.

    return {
      ok: true,
      data: {
        paymentId:     row.payment_id,
        transactionId: row.transaction_id,
        newStatus,
      },
    };
  } catch (e) {
    return { ok: false, error: e.message || 'sbAddSubInvoicePayment failed' };
  }
}

/**
 * Void a payment atomically — voids the sub_invoice_payments row AND the linked
 * job_transactions row (status='void') in a single DB function call.
 * Retains both rows for the audit trail; the payment sum excludes voided rows.
 *
 * Phase 4b: delegates to void_sub_invoice_payment_with_ledger RPC for atomicity.
 *
 * @param {object} params
 * @param {string}  params.paymentId
 * @param {string}  [params.voidReason]
 * @returns {Promise<{ok:boolean, error?:string, data?:{paymentId:string, transactionId:string|null, newStatus:string}}>}
 */
export async function sbVoidSubInvoicePayment({ paymentId, voidReason }) {
  try {
    // Load sub_invoice_id before voiding so we can check accrual after
    const { data: payment } = await sb
      .from('sub_invoice_payments')
      .select('sub_invoice_id')
      .eq('id', paymentId)
      .single();

    const { data, error } = await sb.rpc('void_sub_invoice_payment_with_ledger', {
      p_payment_id:  paymentId,
      p_void_reason: voidReason || null,
    });
    if (error) return { ok: false, error: error.message };
    const row = Array.isArray(data) ? data[0] : data;
    const newStatus = row.new_status;

    // If invoice is no longer fully paid, revert the accrual row back to 'pending'
    if (newStatus !== 'paid' && payment?.sub_invoice_id) {
      const { data: si } = await sb
        .from('sub_invoices')
        .select('accrual_transaction_id')
        .eq('id', payment.sub_invoice_id)
        .single();

      if (si?.accrual_transaction_id) {
        await sb
          .from('job_transactions')
          .update({ status: 'pending', date_paid: null })
          .eq('id', si.accrual_transaction_id)
          .eq('status', 'paid');
      }
    }

    return {
      ok: true,
      data: {
        paymentId:     row.payment_id,
        transactionId: row.transaction_id,
        newStatus,
      },
    };
  } catch (e) {
    return { ok: false, error: e.message || 'sbVoidSubInvoicePayment failed' };
  }
}

/**
 * Creates a pending job_transactions row representing the accrued cost of an
 * approved sub invoice. Idempotent: if sub_invoices.accrual_transaction_id is
 * already populated, returns that row without creating a new one.
 *
 * Only fires on cost_plus jobs — fixed-price jobs don't need it.
 * The Phase 1B trigger (set_cost_plus_defaults_on_jt) stamps
 * reimbursement_status='unreimbursed' + markup_pct automatically on INSERT.
 *
 * @param {string} subInvoiceId
 * @param {number} [overrideAmount]  backfill only — partial remaining balance
 * @returns {Promise<{ok:boolean, error?:string, data?:{transaction_id:string|null, created:boolean}}>}
 */
export async function sbCreateSubInvoiceAccrualRow(subInvoiceId, overrideAmount) {
  if (!subInvoiceId) return { ok: false, error: 'subInvoiceId required', data: null };

  // Load sub invoice
  const { data: si, error: siErr } = await sb
    .from('sub_invoices')
    .select('id, job_id, tenant_id, amount, invoice_number, sub_contact_id, accrual_transaction_id')
    .eq('id', subInvoiceId)
    .single();

  if (siErr) return { ok: false, error: siErr.message, data: null };
  if (!si) return { ok: false, error: 'Sub invoice not found', data: null };

  // Idempotency — already has an accrual row
  if (si.accrual_transaction_id) {
    return { ok: true, error: null, data: { transaction_id: si.accrual_transaction_id, created: false } };
  }

  // Load job to check cost_plus
  const { data: job } = await sb
    .from('jobs')
    .select('id, cost_plus')
    .eq('id', si.job_id)
    .single();

  if (!job?.cost_plus) {
    return { ok: true, error: null, data: { transaction_id: null, created: false } };
  }

  // Resolve payee name
  let payeeName = 'Subcontractor';
  if (si.sub_contact_id) {
    const { data: contact } = await sb
      .from('contacts')
      .select('name')
      .eq('id', si.sub_contact_id)
      .single();
    if (contact?.name) payeeName = contact.name;
  }

  const accrualAmount = overrideAmount !== undefined ? overrideAmount : Number(si.amount);

  // Insert pending job_transactions row.
  // Trigger stamps reimbursement_status='unreimbursed' + markup_pct automatically.
  const { data: tx, error: txErr } = await sb
    .from('job_transactions')
    .insert({
      tenant_id:           si.tenant_id,
      job_id:              si.job_id,
      direction:           'out',
      type:                'sub_payout',
      status:              'pending',
      amount:              accrualAmount,
      date_incurred:       new Date().toISOString().slice(0, 10),
      description:         `Accrued — ${si.invoice_number || 'sub invoice'} (approved, not yet paid)`,
      payer_or_payee_name: payeeName,
      invoice_id:          null,
      created_by:          AV_USER_ID,
    })
    .select('id')
    .single();

  if (txErr) return { ok: false, error: txErr.message, data: null };

  // Link sub_invoice → accrual row
  const { error: linkErr } = await sb
    .from('sub_invoices')
    .update({ accrual_transaction_id: tx.id })
    .eq('id', si.id);

  if (linkErr) {
    // Roll back the insert if link fails
    await sb.from('job_transactions').delete().eq('id', tx.id);
    return { ok: false, error: `Failed to link accrual: ${linkErr.message}`, data: null };
  }

  return { ok: true, error: null, data: { transaction_id: tx.id, created: true } };
}

/**
 * Approve an invoice. Sets approved_at + approved_by_id.
 * On cost_plus jobs, also creates a pending accrual job_transactions row.
 * RLS restricts UPDATE to owner/PM — role gate is enforced at the DB level.
 *
 * @param {object} params
 * @param {string}  params.subInvoiceId
 * @returns {Promise<{ok:boolean, error?:string, data?:{approvedAt:string, accrual:{transaction_id:string|null,created:boolean}|null}}>}
 */
export async function sbApproveSubInvoice({ subInvoiceId }) {
  try {
    const { data: inv, error: fetchErr } = await sb
      .from('sub_invoices')
      .select('disputed, voided_at, approved_at')
      .eq('id', subInvoiceId)
      .single();

    if (fetchErr || !inv) return { ok: false, error: 'Invoice not found' };
    if (inv.voided_at)    return { ok: false, error: 'Cannot approve a voided invoice' };
    if (inv.disputed)     return { ok: false, error: 'Resolve dispute before approving' };
    if (inv.approved_at)  return { ok: false, error: 'Invoice is already approved' };

    const now = new Date().toISOString();
    const { error: updateErr } = await sb
      .from('sub_invoices')
      .update({ approved_at: now, approved_by_id: AV_USER_ID })
      .eq('id', subInvoiceId);

    if (updateErr) return { ok: false, error: updateErr.message };

    // Create accrual row (non-fatal if it fails)
    const accrualResult = await sbCreateSubInvoiceAccrualRow(subInvoiceId);
    if (!accrualResult.ok) {
      console.error('sbApproveSubInvoice accrual creation failed:', accrualResult.error);
    }

    return {
      ok: true,
      data: {
        approvedAt: now,
        accrual: accrualResult.ok ? accrualResult.data : null,
      },
    };
  } catch (e) {
    return { ok: false, error: e.message || 'sbApproveSubInvoice failed' };
  }
}

/**
 * Toggle dispute state on/off.
 * disputed=true freezes payment and approval actions.
 * disputed=false (resolve) restores normal flow.
 *
 * @param {object} params
 * @param {string}   params.subInvoiceId
 * @param {boolean}  params.disputed
 * @param {string}   [params.disputeReason]  required when disputed=true
 * @returns {Promise<{ok:boolean, error?:string}>}
 */
export async function sbDisputeSubInvoice({ subInvoiceId, disputed, disputeReason }) {
  try {
    const { data: inv, error: fetchErr } = await sb
      .from('sub_invoices')
      .select('voided_at, accrual_transaction_id')
      .eq('id', subInvoiceId)
      .single();

    if (fetchErr || !inv) return { ok: false, error: 'Invoice not found' };
    if (inv.voided_at)    return { ok: false, error: 'Cannot dispute a voided invoice' };

    const patch = disputed
      ? {
          disputed:        true,
          disputed_at:     new Date().toISOString(),
          disputed_by_id:  AV_USER_ID,
          dispute_reason:  disputeReason || null,
        }
      : {
          disputed:        false,
          disputed_at:     null,
          disputed_by_id:  null,
          dispute_reason:  null,
        };

    const { error: updateErr } = await sb
      .from('sub_invoices')
      .update(patch)
      .eq('id', subInvoiceId);

    if (updateErr) return { ok: false, error: updateErr.message };

    // Accrual row cascade: cancel on dispute, restore on resolve
    if (inv.accrual_transaction_id) {
      if (disputed) {
        await sb
          .from('job_transactions')
          .update({ status: 'cancelled' })
          .eq('id', inv.accrual_transaction_id)
          .in('status', ['pending', 'paid']);
      } else {
        // Resolve: determine appropriate restore state from current payment sum
        const { data: payments } = await sb
          .from('sub_invoice_payments')
          .select('amount')
          .eq('sub_invoice_id', subInvoiceId)
          .is('voided_at', null);
        const { data: siAmt } = await sb
          .from('sub_invoices')
          .select('amount')
          .eq('id', subInvoiceId)
          .single();
        const paidSum = (payments || []).reduce((s, p) => s + Number(p.amount || 0), 0);
        const fullyPaid = siAmt && paidSum >= Number(siAmt.amount);
        await sb
          .from('job_transactions')
          .update({ status: fullyPaid ? 'paid' : 'pending' })
          .eq('id', inv.accrual_transaction_id)
          .eq('status', 'cancelled');
      }
    }

    return { ok: true };
  } catch (e) {
    return { ok: false, error: e.message || 'sbDisputeSubInvoice failed' };
  }
}

/**
 * Edit invoice fields.
 * If amount is provided, validates that new amount >= sum of non-voided payments.
 *
 * @param {object} params
 * @param {string}  params.subInvoiceId
 * @param {number}  [params.amount]
 * @param {string}  [params.invoiceDate]            YYYY-MM-DD
 * @param {string}  [params.dueDate]                YYYY-MM-DD or null to clear
 * @param {string}  [params.description]
 * @param {Array}   [params.lineItems]              null to clear
 * @param {string}  [params.relatedScheduleItemId]  null to clear
 * @returns {Promise<{ok:boolean, error?:string}>}
 */
export async function sbEditSubInvoice({
  subInvoiceId,
  amount,
  invoiceDate,
  dueDate,
  description,
  lineItems,
  relatedScheduleItemId,
}) {
  try {
    // If changing amount, validate against already-paid sum
    if (amount !== undefined) {
      const { data: payments } = await sb
        .from('sub_invoice_payments')
        .select('amount')
        .eq('sub_invoice_id', subInvoiceId)
        .is('voided_at', null);

      const paidSum = (payments || []).reduce((s, p) => s + Number(p.amount || 0), 0);
      if (amount < paidSum) {
        return {
          ok: false,
          error: `New amount ($${amount.toFixed(2)}) is less than already-paid sum ($${paidSum.toFixed(2)}). Void payment(s) first.`,
        };
      }
    }

    // Build patch from only the fields that were explicitly passed
    const patch = {};
    if (amount !== undefined)                   patch.amount = amount;
    if (invoiceDate !== undefined)              patch.invoice_date = invoiceDate;
    if ('dueDate' in arguments[0])             patch.due_date = dueDate ?? null;
    if ('description' in arguments[0])         patch.description = description ?? null;
    if ('lineItems' in arguments[0])           patch.line_items = lineItems ?? null;
    if ('relatedScheduleItemId' in arguments[0]) patch.related_schedule_item_id = relatedScheduleItemId ?? null;

    if (Object.keys(patch).length === 0) return { ok: true }; // nothing to update

    const { error: updateErr } = await sb
      .from('sub_invoices')
      .update(patch)
      .eq('id', subInvoiceId);

    if (updateErr) return { ok: false, error: updateErr.message };
    return { ok: true };
  } catch (e) {
    return { ok: false, error: e.message || 'sbEditSubInvoice failed' };
  }
}

/**
 * Load all invoices for a job with derived status, paid sum, balance, and payment history.
 *
 * Status is derived per-row via compute_sub_invoice_status RPC.
 * paidSum and balance are computed in JS from the payments array.
 *
 * @param {object} params
 * @param {string}  params.jobId
 * @returns {Promise<{ok:boolean, error?:string, data?:Array}>}
 */
export async function sbLoadSubInvoices({ jobId }) {
  try {
    // Load invoices with sub contact name + all payments
    const { data: invoices, error: invErr } = await sb
      .from('sub_invoices')
      .select(`
        id,
        invoice_number,
        auto_generated_number,
        sub_contact_id,
        invoice_date,
        due_date,
        amount,
        description,
        line_items,
        invoice_file_id,
        lien_waiver_file_id,
        related_schedule_item_id,
        accrual_transaction_id,
        approved_at,
        approved_by_id,
        disputed,
        dispute_reason,
        voided_at,
        voided_by_id,
        void_reason,
        submitted_via,
        created_at,
        sub_contact:contacts!sub_contact_id(name),
        payments:sub_invoice_payments(
          id,
          amount,
          paid_date,
          method,
          reference,
          notes,
          voided_at,
          void_reason,
          transaction_id
        )
      `)
      .eq('job_id', jobId)
      .order('invoice_date', { ascending: false });

    if (invErr) return { ok: false, error: invErr.message };

    // Enrich each invoice with derived status (via RPC) + computed financials
    const enriched = await Promise.all(
      (invoices || []).map(async (inv) => {
        // Compute paid sum from non-voided payments (JS — no extra RPC needed)
        const nonVoidedPayments = (inv.payments || []).filter(p => !p.voided_at);
        const paidSum = nonVoidedPayments.reduce((s, p) => s + Number(p.amount || 0), 0);
        const balance = Math.max(0, Number(inv.amount) - paidSum);

        // Call RPC for source-of-truth status (handles all edge cases in one place)
        const { data: status } = await sb
          .rpc('compute_sub_invoice_status', { p_invoice_id: inv.id });

        return {
          id:                      inv.id,
          invoiceNumber:           inv.invoice_number,
          autoGeneratedNumber:     inv.auto_generated_number,
          subContactId:            inv.sub_contact_id,
          subName:                 inv.sub_contact?.name || '—',
          invoiceDate:             inv.invoice_date,
          dueDate:                 inv.due_date,
          amount:                  Number(inv.amount),
          paidSum,
          balance,
          status:                  status || 'unknown',
          approvedAt:              inv.approved_at,
          approvedById:            inv.approved_by_id,
          disputed:                inv.disputed,
          disputeReason:           inv.dispute_reason,
          voidedAt:                inv.voided_at,
          voidedById:              inv.voided_by_id,
          voidReason:              inv.void_reason,
          invoiceFileId:           inv.invoice_file_id,
          lienWaiverFileId:        inv.lien_waiver_file_id,
          relatedScheduleItemId:   inv.related_schedule_item_id,
          accrualTransactionId:    inv.accrual_transaction_id,
          description:             inv.description,
          lineItems:               inv.line_items,
          submittedVia:            inv.submitted_via,
          createdAt:               inv.created_at,
          payments: (inv.payments || []).map(p => ({
            id:            p.id,
            amount:        Number(p.amount),
            paidDate:      p.paid_date,
            method:        p.method,
            reference:     p.reference,
            notes:         p.notes,
            voidedAt:      p.voided_at,
            voidReason:    p.void_reason,
            transactionId: p.transaction_id,
          })),
        };
      })
    );

    return { ok: true, data: enriched };
  } catch (e) {
    return { ok: false, error: e.message || 'sbLoadSubInvoices failed' };
  }
}

/**
 * Create a new sub/vendor contact.
 * Wraps sbSaveContact with type='sub'. Used by AddInvoiceModal when a
 * vendor name typed (or extracted by AI) does not match an existing contact.
 *
 * @param {{ name: string, phone?: string, email?: string }} params
 * @returns {{ ok: boolean, error: string|null, data: { id: string, name: string }|null }}
 */
export async function sbCreateSubContact({ name, phone, email }) {
  if (!name?.trim()) return { ok: false, error: 'Name is required', data: null };
  const res = await sbSaveContact({
    name:  name.trim(),
    type:  'sub',
    phone: phone?.trim() || null,
    email: email?.trim() || null,
  });
  if (!res.ok) return { ok: false, error: res.error, data: null };
  return { ok: true, error: null, data: { id: res.data.id, name: res.data.name } };
}

/**
 * Void a sub invoice and cascade void to all its non-voided payments.
 * Each payment void calls Phase 4b's void_sub_invoice_payment_with_ledger
 * atomically (ledger reversal per payment). Audit trail preserved — no hard deletes.
 *
 * @param {{ subInvoiceId: string, voidReason: string }} params
 * @returns {Promise<{ok:boolean, error?:string, data?:{invoiceId:string, paymentsVoided:number}}>}
 */
export async function sbVoidSubInvoice({ subInvoiceId, voidReason }) {
  try {
    const { data, error } = await sb.rpc('void_sub_invoice_with_cascade', {
      p_invoice_id:  subInvoiceId,
      p_void_reason: voidReason,
    });
    if (error) return { ok: false, error: error.message };
    const row = Array.isArray(data) ? data[0] : data;
    return { ok: true, data: { invoiceId: row.invoice_id, paymentsVoided: row.payments_voided } };
  } catch (e) {
    return { ok: false, error: e.message || 'sbVoidSubInvoice failed' };
  }
}

/**
 * Un-void a previously voided sub invoice.
 * Only clears voided_at / voided_by_id / void_reason on the invoice itself.
 * Cascaded payments stay voided — user re-records fresh payments after restoring.
 *
 * @param {{ subInvoiceId: string }} params
 * @returns {Promise<{ok:boolean, error?:string}>}
 */
export async function sbUnvoidSubInvoice({ subInvoiceId }) {
  try {
    const { error } = await sb.rpc('unvoid_sub_invoice', {
      p_invoice_id: subInvoiceId,
    });
    if (error) return { ok: false, error: error.message };
    return { ok: true };
  } catch (e) {
    return { ok: false, error: e.message || 'sbUnvoidSubInvoice failed' };
  }
}
