-- Seed 6 platform-default room-type templates for takeoff_templates.
-- tenant_id = NULL means every tenant inherits these rows via the updated
-- RLS policy (tenant_id = get_my_tenant_id() OR tenant_id IS NULL).
-- One row per (trade, room_type) pair. scope_definition JSONB holds per-trade
-- scope details, optional flag, and conditional note.
-- Trade strings use canonical taxonomy format: "Parent - Sub" for sub-trades,
-- plain "Parent" for top-level trades (Demo, Framing, Roofing, etc.).

INSERT INTO takeoff_templates (tenant_id, trade, room_type, name, scope_definition, active, created_by) VALUES

-- ============================================================
-- BATHROOM REMODEL (room_type = 'bathroom')
-- ============================================================
(NULL, 'Demo',                         'bathroom', 'Bathroom remodel - Demo',                         '{"summary":"Full gut demo — remove tile, fixtures, vanity, drywall as needed","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Plumbing - Rough-in',          'bathroom', 'Bathroom remodel - Plumbing - Rough-in',          '{"summary":"Rough-in supply and drain lines for tub/shower, toilet, and vanity sink","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Plumbing - Finish / fixtures', 'bathroom', 'Bathroom remodel - Plumbing - Finish / fixtures', '{"summary":"Set toilet, faucets, shower valve, tub/shower trim","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Electrical - Rough-in',        'bathroom', 'Bathroom remodel - Electrical - Rough-in',        '{"summary":"Rough-in circuits for lighting, exhaust fan, GFCI outlets","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Electrical - Finish',          'bathroom', 'Bathroom remodel - Electrical - Finish',          '{"summary":"Install fixtures, exhaust fan, GFCI outlets, switches","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Drywall - Hang',               'bathroom', 'Bathroom remodel - Drywall - Hang',               '{"summary":"Hang cement board in wet areas, moisture-resistant drywall elsewhere","optional":false,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Drywall - Tape / mud / texture','bathroom', 'Bathroom remodel - Drywall - Tape / mud / texture','{"summary":"Tape, mud, and texture non-tiled drywall surfaces","optional":false,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Tile - Floor',                 'bathroom', 'Bathroom remodel - Tile - Floor',                 '{"summary":"Floor tile including substrate prep, mortar, grout, sealer","optional":false,"conditional":null,"default_unit":"sf","waste_pct":15}', true, NULL),
(NULL, 'Tile - Wall / shower',         'bathroom', 'Bathroom remodel - Tile - Wall / shower',         '{"summary":"Shower and tub surround tile including niche, curb, and waterproofing membrane","optional":false,"conditional":null,"default_unit":"sf","waste_pct":15}', true, NULL),
(NULL, 'Cabinets / vanities - Install','bathroom', 'Bathroom remodel - Cabinets / vanities - Install','{"summary":"Set and level vanity cabinet, attach countertop, install mirror","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Paint - Interior',             'bathroom', 'Bathroom remodel - Paint - Interior',             '{"summary":"Prime and paint walls and ceiling, moisture-resistant paint in wet zones","optional":false,"conditional":null,"default_unit":"sf","waste_pct":null}', true, NULL),
(NULL, 'Trim / carpentry - Base / case','bathroom','Bathroom remodel - Trim / carpentry - Base / case','{"summary":"Install baseboard and door casing, caulk and paint","optional":false,"conditional":null,"default_unit":"lf","waste_pct":10}', true, NULL),
(NULL, 'Flooring - LVP',               'bathroom', 'Bathroom remodel - Flooring - LVP',               '{"summary":"LVP flooring as alternate to tile floor — waterproof click-lock installation","optional":true,"conditional":"alternate to Tile - Floor","default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Cleanup',                      'bathroom', 'Bathroom remodel - Cleanup',                      '{"summary":"Final clean, haul debris, protect finish surfaces during punch","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),

-- ============================================================
-- KITCHEN REMODEL (room_type = 'kitchen')
-- ============================================================
(NULL, 'Demo',                         'kitchen', 'Kitchen remodel - Demo',                         '{"summary":"Demo cabinets, countertops, backsplash tile, flooring as needed","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Plumbing - Rough-in',          'kitchen', 'Kitchen remodel - Plumbing - Rough-in',          '{"summary":"Rough-in supply and drain for sink; stub for dishwasher and ice maker if needed","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Plumbing - Finish / fixtures', 'kitchen', 'Kitchen remodel - Plumbing - Finish / fixtures', '{"summary":"Set kitchen faucet, garbage disposal, dishwasher supply and drain connections","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Electrical - Rough-in',        'kitchen', 'Kitchen remodel - Electrical - Rough-in',        '{"summary":"Rough-in circuits for appliances, under-cabinet lighting, GFCI outlets","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Electrical - Finish',          'kitchen', 'Kitchen remodel - Electrical - Finish',          '{"summary":"Install outlets, under-cabinet lights, switches, appliance connections","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Drywall - Patch',              'kitchen', 'Kitchen remodel - Drywall - Patch',              '{"summary":"Patch drywall after cabinet and plumbing/electrical changes","optional":false,"conditional":null,"default_unit":"sf","waste_pct":null}', true, NULL),
(NULL, 'Drywall - Tape / mud / texture','kitchen', 'Kitchen remodel - Drywall - Tape / mud / texture','{"summary":"Feather and texture patched areas to match existing","optional":false,"conditional":null,"default_unit":"sf","waste_pct":null}', true, NULL),
(NULL, 'Cabinets / vanities - Install','kitchen', 'Kitchen remodel - Cabinets / vanities - Install','{"summary":"Install upper and lower cabinets, crown molding on uppers, hardware","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Tile - Backsplash',            'kitchen', 'Kitchen remodel - Tile - Backsplash',            '{"summary":"Backsplash tile between countertop and uppers — substrate, mortar, grout, sealer","optional":false,"conditional":null,"default_unit":"sf","waste_pct":15}', true, NULL),
(NULL, 'Flooring - LVP',               'kitchen', 'Kitchen remodel - Flooring - LVP',               '{"summary":"Waterproof LVP flooring — click-lock installation over existing subfloor","optional":false,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Flooring - Hardwood',          'kitchen', 'Kitchen remodel - Flooring - Hardwood',          '{"summary":"Hardwood flooring as alternate — nail/glue down, sand and finish","optional":true,"conditional":"alternate to Flooring - LVP","default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Paint - Interior',             'kitchen', 'Kitchen remodel - Paint - Interior',             '{"summary":"Prime and paint walls and ceiling","optional":false,"conditional":null,"default_unit":"sf","waste_pct":null}', true, NULL),
(NULL, 'Paint - Cabinet refinish',     'kitchen', 'Kitchen remodel - Paint - Cabinet refinish',     '{"summary":"Refinish existing cabinet boxes and doors — sand, prime, spray finish — as alternate to new cabinets","optional":true,"conditional":"alternate to new cabinet install","default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Trim / carpentry - Base / case','kitchen', 'Kitchen remodel - Trim / carpentry - Base / case','{"summary":"Replace or refit baseboard and door casing disturbed by floor/cabinet work","optional":false,"conditional":null,"default_unit":"lf","waste_pct":10}', true, NULL),
(NULL, 'Appliances',                   'kitchen', 'Kitchen remodel - Appliances',                   '{"summary":"Supply and set refrigerator, range/oven, dishwasher, microwave/hood","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Cleanup',                      'kitchen', 'Kitchen remodel - Cleanup',                      '{"summary":"Final clean, haul debris, remove appliance packaging","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),

-- ============================================================
-- BASEMENT FINISH (room_type = 'basement')
-- ============================================================
(NULL, 'Framing',                      'basement', 'Basement finish - Framing',                      '{"summary":"Frame perimeter and partition walls, soffits, and mechanical chases","optional":false,"conditional":null,"default_unit":"lf","waste_pct":10}', true, NULL),
(NULL, 'Insulation',                   'basement', 'Basement finish - Insulation',                   '{"summary":"Insulate perimeter walls and ceiling as required by code","optional":false,"conditional":null,"default_unit":"sf","waste_pct":5}', true, NULL),
(NULL, 'Plumbing - Rough-in',          'basement', 'Basement finish - Plumbing - Rough-in',          '{"summary":"Rough-in supply and drain for bathroom or kitchenette","optional":true,"conditional":"if bathroom or kitchenette in scope","default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Plumbing - Finish / fixtures', 'basement', 'Basement finish - Plumbing - Finish / fixtures', '{"summary":"Set fixtures for basement bathroom or kitchenette","optional":true,"conditional":"if bathroom or kitchenette in scope","default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Electrical - Rough-in',        'basement', 'Basement finish - Electrical - Rough-in',        '{"summary":"Rough-in circuits for lighting, outlets, dedicated loads","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Electrical - Finish',          'basement', 'Basement finish - Electrical - Finish',          '{"summary":"Install fixtures, outlets, switches, panel circuits","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Electrical - Low voltage',     'basement', 'Basement finish - Electrical - Low voltage',     '{"summary":"Structured wiring — ethernet, coax, speakers, security — as required","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'HVAC - Install',               'basement', 'Basement finish - HVAC - Install',               '{"summary":"Extend existing ductwork or install supplemental unit for conditioned space","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Drywall - Hang',               'basement', 'Basement finish - Drywall - Hang',               '{"summary":"Hang drywall on framed walls and ceiling throughout finished area","optional":false,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Drywall - Tape / mud / texture','basement','Basement finish - Drywall - Tape / mud / texture','{"summary":"Tape, mud, and texture all drywall surfaces","optional":false,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Paint - Interior',             'basement', 'Basement finish - Paint - Interior',             '{"summary":"Prime and paint all walls, ceiling, and trim in finished area","optional":false,"conditional":null,"default_unit":"sf","waste_pct":null}', true, NULL),
(NULL, 'Flooring - LVP',               'basement', 'Basement finish - Flooring - LVP',               '{"summary":"Waterproof LVP over concrete slab — floating installation with moisture barrier","optional":false,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Flooring - Carpet',            'basement', 'Basement finish - Flooring - Carpet',            '{"summary":"Carpet with pad as alternate to LVP in bedroom or living areas","optional":true,"conditional":"alternate to Flooring - LVP","default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Trim / carpentry - Base / case','basement','Basement finish - Trim / carpentry - Base / case','{"summary":"Install baseboard and door casing throughout finished space","optional":false,"conditional":null,"default_unit":"lf","waste_pct":10}', true, NULL),
(NULL, 'Tile - Floor',                 'basement', 'Basement finish - Tile - Floor',                 '{"summary":"Floor tile for bathroom or utility area in basement","optional":true,"conditional":"if bathroom in scope","default_unit":"sf","waste_pct":15}', true, NULL),
(NULL, 'Tile - Wall / shower',         'basement', 'Basement finish - Tile - Wall / shower',         '{"summary":"Shower surround tile for basement bathroom","optional":true,"conditional":"if bathroom in scope","default_unit":"sf","waste_pct":15}', true, NULL),
(NULL, 'Cabinets / vanities - Install','basement', 'Basement finish - Cabinets / vanities - Install','{"summary":"Vanity or kitchenette cabinet install in basement bathroom or wet bar","optional":true,"conditional":"if kitchenette or bathroom in scope","default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Cleanup',                      'basement', 'Basement finish - Cleanup',                      '{"summary":"Final clean, haul construction debris, sweep and vacuum finished space","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),

-- ============================================================
-- PAINT AND FLOOR REFRESH (room_type = 'refresh')
-- ============================================================
(NULL, 'Paint - Interior',             'refresh', 'Paint and floor refresh - Paint - Interior',             '{"summary":"Prime and paint all interior walls and ceilings — full house","optional":false,"conditional":null,"default_unit":"sf","waste_pct":null}', true, NULL),
(NULL, 'Trim / carpentry - Base / case','refresh', 'Paint and floor refresh - Trim / carpentry - Base / case','{"summary":"Replace baseboard and casing damaged or removed during floor transition","optional":true,"conditional":"replace if damaged during floor work","default_unit":"lf","waste_pct":10}', true, NULL),
(NULL, 'Flooring - LVP',               'refresh', 'Paint and floor refresh - Flooring - LVP',               '{"summary":"Whole-house LVP replacement — demo existing, install floating floor","optional":false,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Flooring - Hardwood',          'refresh', 'Paint and floor refresh - Flooring - Hardwood',          '{"summary":"Solid or engineered hardwood as alternate to LVP","optional":true,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Flooring - Carpet',            'refresh', 'Paint and floor refresh - Flooring - Carpet',            '{"summary":"Carpet with pad in bedrooms or lower level as alternate to hard surface","optional":true,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Flooring - Laminate',          'refresh', 'Paint and floor refresh - Flooring - Laminate',          '{"summary":"Laminate flooring as budget alternate to LVP","optional":true,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Cleanup',                      'refresh', 'Paint and floor refresh - Cleanup',                      '{"summary":"Final clean, haul flooring and paint debris","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),

-- ============================================================
-- ADDITION - SINGLE ROOM (room_type = 'addition')
-- ============================================================
(NULL, 'Demo',                         'addition', 'Addition - single room - Demo',                         '{"summary":"Open existing exterior wall for addition tie-in — remove sheathing, framing, interior finishes at penetration","optional":false,"conditional":"existing exterior wall opening","default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Foundations - Poured',         'addition', 'Addition - single room - Foundations - Poured',         '{"summary":"Poured concrete foundation walls and footings for addition","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Foundations - Block',          'addition', 'Addition - single room - Foundations - Block',          '{"summary":"CMU block foundation as alternate to poured concrete","optional":true,"conditional":"alternate to Foundations - Poured","default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Foundations - ICF',            'addition', 'Addition - single room - Foundations - ICF',            '{"summary":"Insulated concrete form foundation as alternate to poured concrete","optional":true,"conditional":"alternate to Foundations - Poured","default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Concrete - Footings',          'addition', 'Addition - single room - Concrete - Footings',          '{"summary":"Pour continuous footings below frost line per structural plan","optional":false,"conditional":null,"default_unit":"lf","waste_pct":5}', true, NULL),
(NULL, 'Concrete - Slabs',             'addition', 'Addition - single room - Concrete - Slabs',             '{"summary":"Pour interior slab on grade with vapor barrier and wire mesh","optional":false,"conditional":null,"default_unit":"sf","waste_pct":5}', true, NULL),
(NULL, 'Framing',                      'addition', 'Addition - single room - Framing',                      '{"summary":"Frame exterior walls, roof structure, and interior partitions for addition","optional":false,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Roofing',                      'addition', 'Addition - single room - Roofing',                      '{"summary":"Addition roof — sheathing, underlayment, shingles, and tie-in flashing to existing","optional":false,"conditional":null,"default_unit":"sq","waste_pct":10}', true, NULL),
(NULL, 'Insulation',                   'addition', 'Addition - single room - Insulation',                   '{"summary":"Insulate walls, ceiling, and rim joist to match or exceed existing house envelope","optional":false,"conditional":null,"default_unit":"sf","waste_pct":5}', true, NULL),
(NULL, 'Plumbing - Rough-in',          'addition', 'Addition - single room - Plumbing - Rough-in',          '{"summary":"Rough-in supply and drain if addition includes wet areas","optional":true,"conditional":"if scope includes plumbing","default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Plumbing - Finish / fixtures', 'addition', 'Addition - single room - Plumbing - Finish / fixtures', '{"summary":"Set fixtures in addition if plumbing is in scope","optional":true,"conditional":"if scope includes plumbing","default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Electrical - Rough-in',        'addition', 'Addition - single room - Electrical - Rough-in',        '{"summary":"Rough-in circuits for lighting, outlets, and any dedicated loads in addition","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Electrical - Finish',          'addition', 'Addition - single room - Electrical - Finish',          '{"summary":"Install fixtures, outlets, and switches; tie into existing panel","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'HVAC - Install',               'addition', 'Addition - single room - HVAC - Install',               '{"summary":"Extend existing ductwork into addition or install supplemental mini-split","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),
(NULL, 'Drywall - Hang',               'addition', 'Addition - single room - Drywall - Hang',               '{"summary":"Hang drywall on all addition walls and ceiling","optional":false,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Drywall - Tape / mud / texture','addition','Addition - single room - Drywall - Tape / mud / texture','{"summary":"Tape, mud, and texture addition drywall to match existing interior","optional":false,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Paint - Interior',             'addition', 'Addition - single room - Paint - Interior',             '{"summary":"Prime and paint addition interior walls and ceiling","optional":false,"conditional":null,"default_unit":"sf","waste_pct":null}', true, NULL),
(NULL, 'Paint - Exterior',             'addition', 'Addition - single room - Paint - Exterior',             '{"summary":"Paint addition exterior siding and trim to match existing house","optional":false,"conditional":"match existing","default_unit":"sf","waste_pct":null}', true, NULL),
(NULL, 'Flooring - LVP',               'addition', 'Addition - single room - Flooring - LVP',               '{"summary":"LVP flooring in addition — match or complement existing house flooring","optional":true,"conditional":null,"default_unit":"sf","waste_pct":10}', true, NULL),
(NULL, 'Trim / carpentry - Base / case','addition','Addition - single room - Trim / carpentry - Base / case','{"summary":"Install baseboard, door casing, and window casing in addition to match existing","optional":false,"conditional":null,"default_unit":"lf","waste_pct":10}', true, NULL),
(NULL, 'Trim / carpentry - Crown',     'addition', 'Addition - single room - Trim / carpentry - Crown',     '{"summary":"Crown molding in addition if present in adjacent existing space","optional":true,"conditional":null,"default_unit":"lf","waste_pct":10}', true, NULL),
(NULL, 'Cleanup',                      'addition', 'Addition - single room - Cleanup',                      '{"summary":"Final clean addition interior and exterior, haul debris","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL),

-- ============================================================
-- EXTERIOR REFRESH (room_type = 'exterior')
-- ============================================================
(NULL, 'Paint - Exterior',             'exterior', 'Exterior refresh - Paint - Exterior',             '{"summary":"Pressure wash, prime, and paint all exterior siding, trim, and soffits","optional":false,"conditional":null,"default_unit":"sf","waste_pct":null}', true, NULL),
(NULL, 'Trim / carpentry - Base / case','exterior', 'Exterior refresh - Trim / carpentry - Base / case','{"summary":"Repair or replace rotted/damaged exterior trim boards and casing","optional":false,"conditional":"exterior trim repair/replace","default_unit":"lf","waste_pct":10}', true, NULL),
(NULL, 'Garage door',                  'exterior', 'Exterior refresh - Garage door',                  '{"summary":"Replace garage door and opener — includes new tracks, springs, and haul-away","optional":true,"conditional":"replace if in scope","default_unit":"ea","waste_pct":null}', true, NULL),
(NULL, 'Cleanup',                      'exterior', 'Exterior refresh - Cleanup',                      '{"summary":"Haul exterior debris, clean paint overspray, restore landscape protection","optional":false,"conditional":null,"default_unit":"ls","waste_pct":null}', true, NULL);
