-- SCE Phase 1B · FULL SEED — 9 project types + 15 modules (14 draft + waterproofing) + conflict rules.
-- Translated verbatim from docs/arcs/SCOPE_SEED_CONTENT_DRAFT.md (owner-locked 2026-07-10).
-- ALL rows tenant_id = NULL (platform defaults). Idempotent + re-runnable: upserts ON CONFLICT
-- per the NULLS-NOT-DISTINCT natural keys. money_risk_rank sequential per type in document order.
-- Generated from tools/gen_sce_seed.cjs — do not hand-edit; regenerate after a draft red-pen.

BEGIN;

-- Bathroom reconciliation: drop old-key rows superseded by draft keys (answer persistence
-- does not exist yet, so this is safe). shower_type→tub_shower_config, wall_tile_extent→tile_height,
-- floor_finish→floor_tile, shower_enclosure→shower_glass, shower_niche→niche, vanity_count→(draft vanity split).
DELETE FROM scope_checklists WHERE tenant_id IS NULL AND project_type='bathroom' AND field_key IN ('shower_type','wall_tile_extent','floor_finish','shower_enclosure','shower_niche','vanity_count');

-- BATHROOM (18 fields)
INSERT INTO scope_checklists (tenant_id, project_type, field_key, question, field_type, options, money_risk_rank, adds_trades, audience, risk_note, active) VALUES
  (NULL, 'bathroom', 'tub_shower_config', 'Walk-in shower only, tub/shower combo, freestanding tub plus separate shower, or tub only?', 'choice', '["walkin","combo","freestanding_plus_shower","tub_only"]'::jsonb, 1, ARRAY['Plumbing - Rough-in','Tile - Wall / shower','Tile - Floor']::text[], 'rep_client', 'Drives plumbing rough-in, glass, waterproofing footprint — the single biggest layout fork', true),
  (NULL, 'bathroom', 'layout_change', 'Are fixtures staying where they are, or moving (toilet, vanity, tub/shower)?', 'choice', '["keep_layout","minor_moves","full_reconfigure"]'::jsonb, 2, ARRAY['Plumbing - Rough-in']::text[], 'rep_client', 'Every fixture move = drain + supply relocation; slab foundation makes this brutal', true),
  (NULL, 'bathroom', 'shower_entry', 'Standard curb or curbless/zero-entry shower?', 'choice', '["curb","curbless"]'::jsonb, 3, NULL, 'rep_client', 'Curbless = recessed subfloor or topping slab; joist direction can kill it. Huge missed-cost item', true),
  (NULL, 'bathroom', 'wet_wall_window', 'Is there a window in the shower/tub wet wall? Keep, remove, or replace?', 'choice', '["none","keep_waterproof","remove_infill","replace_smaller"]'::jsonb, 4, NULL, 'rep', 'Window in wet zone = waterproofing detail or framing/siding/exterior patch', true),
  (NULL, 'bathroom', 'tile_height', 'Wall tile to the ceiling, standard height, or wainscot?', 'choice', '["ceiling","standard","wainscot"]'::jsonb, 5, ARRAY['Tile - Wall / shower']::text[], 'rep_client', 'Can double wall-tile quantity + labor', true),
  (NULL, 'bathroom', 'niche', 'Recessed niche, shelf/ledge, corner shelves, or none?', 'choice', '["recessed","shelf","corner","none"]'::jsonb, 6, ARRAY['Tile - Wall / shower']::text[], 'rep_client', 'Niche = framing + waterproofing detail; retrofit after tile = never', true),
  (NULL, 'bathroom', 'wall_tile_layout', 'Tile pattern on walls?', 'choice', '["subway_offset","stacked","herringbone","large_format","hex"]'::jsonb, 7, ARRAY['Tile - Wall / shower']::text[], 'rep_client', 'Herringbone/hex = labor multiplier; large-format = substrate flatness prep', true),
  (NULL, 'bathroom', 'shower_glass', 'Frameless glass, framed door, or curtain?', 'choice', '["frameless","framed","curtain"]'::jsonb, 8, ARRAY['Tile - Wall / shower']::text[], 'rep_client', 'Frameless = $1.5-3k+ line item people forget until the end', true),
  (NULL, 'bathroom', 'shower_drain', 'Standard center drain or linear drain?', 'choice', '["center","linear"]'::jsonb, 9, ARRAY['Tile - Floor']::text[], 'rep', 'Linear = slope-to-one-plane, changes pan build and tile sizes possible', true),
  (NULL, 'bathroom', 'floor_tile', 'Floor material?', 'choice', '["porcelain_woodlook","porcelain_stonelook","natural_stone","lvp"]'::jsonb, 10, ARRAY['Tile - Floor','Flooring - LVP']::text[], 'rep_client', 'Natural stone = sealing + thickness transitions; LVP = budget signal', true),
  (NULL, 'bathroom', 'heated_floor', 'Heated floor?', 'bool', NULL, 11, ARRAY['Electrical - Rough-in']::text[], 'rep_client', 'Electric mat + dedicated circuit + thermostat — retrofit impossible after tile', true),
  (NULL, 'bathroom', 'vanity_style', 'Vanity style?', 'choice', '["floating","freestanding","builtin"]'::jsonb, 12, ARRAY['Cabinets / vanities - Install']::text[], 'rep_client', 'Floating = blocking in wall; size drives plumbing centers', true),
  (NULL, 'bathroom', 'vanity_size_in', 'Vanity size, roughly, in inches?', 'number', NULL, 13, ARRAY['Cabinets / vanities - Install']::text[], 'rep_client', NULL, true),
  (NULL, 'bathroom', 'countertop', 'Vanity top material?', 'choice', '["quartz","granite","cultured_marble"]'::jsonb, 14, NULL, 'rep_client', NULL, true),
  (NULL, 'bathroom', 'fixture_finish', 'Fixture finish family?', 'choice', '["brushed_nickel","matte_black","chrome","brushed_gold"]'::jsonb, 15, ARRAY['Plumbing - Finish / fixtures']::text[], 'rep_client', 'Locks the whole fixture package; mixed finishes = client callback', true),
  (NULL, 'bathroom', 'ventilation', 'Existing exhaust fan — present, and vented where?', 'choice', '["exists_vented_out","exists_vented_attic","none"]'::jsonb, 16, ARRAY['Electrical - Rough-in','Electrical - Finish']::text[], 'rep', 'Attic-vented or missing fan = code fix + roof/soffit penetration nobody quoted', true),
  (NULL, 'bathroom', 'toilet', 'Toilet — reuse, standard replace, comfort-height, wall-hung, or bidet seat circuit?', 'choice', '["reuse","standard","comfort_height","wall_hung","bidet_circuit"]'::jsonb, 17, ARRAY['Plumbing - Finish / fixtures']::text[], 'rep_client', 'Wall-hung = in-wall carrier (framing + cost jump); bidet seat = outlet at toilet', true),
  (NULL, 'bathroom', 'age_of_home', 'Roughly what year was the house built?', 'choice', '["pre_1950","1950_1977","1978_2000","post_2000"]'::jsonb, 18, NULL, 'rep_client', 'Pre-''78 = lead paint protocol; old homes = galvanized/cast-iron surprise territory', true)
ON CONFLICT (tenant_id, project_type, field_key) DO UPDATE SET question=EXCLUDED.question, field_type=EXCLUDED.field_type, options=EXCLUDED.options, money_risk_rank=EXCLUDED.money_risk_rank, adds_trades=EXCLUDED.adds_trades, audience=EXCLUDED.audience, risk_note=EXCLUDED.risk_note, active=true;

-- KITCHEN (16 fields)
INSERT INTO scope_checklists (tenant_id, project_type, field_key, question, field_type, options, money_risk_rank, adds_trades, audience, risk_note, active) VALUES
  (NULL, 'kitchen', 'layout_change', 'Keeping the layout, or moving things — sink, range, fridge locations?', 'choice', '["keep","reconfigure","wall_removal_open_concept"]'::jsonb, 1, ARRAY['Plumbing - Rough-in','Electrical - Rough-in']::text[], 'rep_client', 'THE kitchen fork. Sink move = drain/vent; range move = gas or 240V; wall = structural', true),
  (NULL, 'kitchen', 'wall_removal_detail', 'If a wall is coming out — which wall, and does anything live in it (ducts, plumbing stacks, wiring)?', 'text', NULL, 2, ARRAY['Framing','Demo']::text[], 'rep', 'Load-bearing + HVAC/plumbing in wall = beam + reroutes; the classic $15k surprise', true),
  (NULL, 'kitchen', 'island', 'Island — none, dry, with sink/cooktop, or peninsula?', 'choice', '["none","dry","wet","peninsula"]'::jsonb, 3, ARRAY['Plumbing - Rough-in','Electrical - Rough-in']::text[], 'rep_client', 'Wet island = underslab/underfloor drain + vent (island venting = real plumbing)', true),
  (NULL, 'kitchen', 'cabinets_supply', 'Who supplies cabinets — us, client-purchased, or reuse/refinish existing?', 'choice', '["contractor","client_supplied","reface","paint_existing"]'::jsonb, 4, ARRAY['Cabinets / vanities - Install']::text[], 'rep', 'Supply model = margin model; client-supplied = delivery/damage/missing-filler risk', true),
  (NULL, 'kitchen', 'cabinet_style', 'Door style?', 'choice', '["shaker","slab","raised_panel","inset"]'::jsonb, 5, ARRAY['Cabinets / vanities - Install']::text[], 'rep_client', 'Inset = precision + cost tier jump', true),
  (NULL, 'kitchen', 'uppers', 'Uppers to the ceiling, standard with soffit, open above, or open shelving?', 'choice', '["ceiling","soffit","open_above","open_shelving"]'::jsonb, 6, ARRAY['Cabinets / vanities - Install']::text[], 'rep_client', 'To-ceiling = taller boxes + crown detail; soffit removal = what''s IN the soffit?', true),
  (NULL, 'kitchen', 'countertop', 'Countertop material?', 'choice', '["quartz","granite","butcher_block","laminate"]'::jsonb, 7, NULL, 'rep_client', NULL, true),
  (NULL, 'kitchen', 'counter_edge', 'Edge/detail — eased, waterfall island end, or ogee?', 'choice', '["eased","waterfall","ogee"]'::jsonb, 8, NULL, 'rep_client', 'Waterfall = extra slab + fabrication', true),
  (NULL, 'kitchen', 'sink', 'Sink style?', 'choice', '["undermount_single","farmhouse","dropin"]'::jsonb, 9, ARRAY['Plumbing - Finish / fixtures']::text[], 'rep_client', 'Farmhouse = cabinet modification + weight', true),
  (NULL, 'kitchen', 'backsplash_extent', 'Backsplash extent?', 'choice', '["standard","full_range","full_all"]'::jsonb, 10, ARRAY['Tile - Backsplash']::text[], 'rep_client', NULL, true),
  (NULL, 'kitchen', 'backsplash_layout', 'Backsplash pattern?', 'choice', '["subway","herringbone","stacked","slab"]'::jsonb, 11, ARRAY['Tile - Backsplash']::text[], 'rep_client', NULL, true),
  (NULL, 'kitchen', 'appliances', 'Appliances — who supplies, and any changes in size/location/fuel?', 'choice', '["reuse_all","client_supplied_new","contractor_supplied"]'::jsonb, 12, ARRAY['Electrical - Rough-in']::text[], 'rep_client', '30"→36" range, counter-depth fridge, gas→induction — each is a cabinet/electrical/gas line item', true),
  (NULL, 'kitchen', 'venting', 'Range hood — type, and does it vent outside today?', 'choice', '["undercab","chimney","custom","otr_micro"]'::jsonb, 13, NULL, 'rep', 'Recirculating→vented = new exterior penetration + duct run', true),
  (NULL, 'kitchen', 'flooring_extent', 'New flooring — kitchen only, or flowing into adjacent rooms?', 'choice', '["kitchen_only","contiguous_areas"]'::jsonb, 14, NULL, 'rep_client', '"Match into the living room" doubles the flooring scope; transition height issues', true),
  (NULL, 'kitchen', 'elec_panel', 'Panel capacity — known space for new circuits? (photo of panel)', 'choice', '["room_available","full","unknown"]'::jsonb, 15, ARRAY['Electrical - Service upgrade']::text[], 'rep', 'Kitchen remodel adds 3-6 circuits; full panel = upgrade nobody quoted', true),
  (NULL, 'kitchen', 'age_of_home', 'Year built?', 'choice', '["pre_1950","1950_1977","1978_2000","post_2000"]'::jsonb, 16, NULL, 'rep_client', NULL, true)
ON CONFLICT (tenant_id, project_type, field_key) DO UPDATE SET question=EXCLUDED.question, field_type=EXCLUDED.field_type, options=EXCLUDED.options, money_risk_rank=EXCLUDED.money_risk_rank, adds_trades=EXCLUDED.adds_trades, audience=EXCLUDED.audience, risk_note=EXCLUDED.risk_note, active=true;

-- DECK (12 fields)
INSERT INTO scope_checklists (tenant_id, project_type, field_key, question, field_type, options, money_risk_rank, adds_trades, audience, risk_note, active) VALUES
  (NULL, 'deck', 'size_height', 'Rough size, and how high off grade at the highest point?', 'choice', '["low_under_30in","mid","second_story"]'::jsonb, 1, ARRAY['Concrete - Footings']::text[], 'rep_client', '>30" = guardrail code + footing depth; second-story = beam sizing + stairs become a structure', true),
  (NULL, 'deck', 'attachment', 'Attached with a ledger, or freestanding?', 'choice', '["ledger","freestanding"]'::jsonb, 2, NULL, 'rep', 'Ledger = flashing detail + what’s behind the siding (rot discovery zone); freestanding = more footings', true),
  (NULL, 'deck', 'existing_deck', 'Existing deck — none, full tearoff, or reuse framing?', 'choice', '["none","tearoff","reuse_framing"]'::jsonb, 3, ARRAY['Demo']::text[], 'rep', '"Reuse framing" = inspect joists/footings; composite on old 24" OC framing = fail', true),
  (NULL, 'deck', 'material', 'Decking material?', 'choice', '["pt","cedar","composite","pvc"]'::jsonb, 4, NULL, 'rep_client', '3-4× material spread; composite = 16" OC or better framing', true),
  (NULL, 'deck', 'board_layout', 'Board pattern?', 'choice', '["standard","diagonal","picture_frame","breaker"]'::jsonb, 5, NULL, 'rep_client', 'Diagonal/picture-frame = waste factor + blocking', true),
  (NULL, 'deck', 'railing', 'Railing style?', 'choice', '["wood_baluster","metal_baluster","cable","aluminum","glass"]'::jsonb, 6, NULL, 'rep_client', 'Cable/glass = 2-5× rail cost; cable = post engineering for tension', true),
  (NULL, 'deck', 'stairs', 'Stairs — none, straight, landing, or wrap/cascade?', 'choice', '["none","straight","landing","cascade"]'::jsonb, 7, NULL, 'rep_client', 'Stairs are per-step money; landing = footings', true),
  (NULL, 'deck', 'overhead', 'Anything overhead — pergola, full covered roof, or louvered?', 'choice', '["none","pergola","roof","louvered"]'::jsonb, 8, ARRAY['Framing']::text[], 'rep_client', 'Covered roof = tie into house roof + posts sized up + permit becomes structure', true),
  (NULL, 'deck', 'under_deck', 'Under-deck treatment?', 'choice', '["open","skirting","dry_below"]'::jsonb, 9, NULL, 'rep_client', 'Dry-below = drainage system + gutter, real line item', true),
  (NULL, 'deck', 'fastening', 'Face-screw or hidden fasteners?', 'choice', '["face","hidden"]'::jsonb, 10, NULL, 'rep_client', NULL, true),
  (NULL, 'deck', 'electrical', 'Lighting/outlets/fan on the deck?', 'choice', '["none","lighting","outlets","fan_on_covered"]'::jsonb, 11, ARRAY['Electrical - Rough-in']::text[], 'rep_client', 'Exterior circuit + GFCI; fan needs the covered roof answered', true),
  (NULL, 'deck', 'utilities_below', 'Anything where footings go — utilities, septic, irrigation? Locate scheduled?', 'choice', '["clear","unknown_locate_needed","known_conflicts"]'::jsonb, 12, ARRAY['Concrete - Footings']::text[], 'rep', 'Footing hits septic line = bad day', true)
ON CONFLICT (tenant_id, project_type, field_key) DO UPDATE SET question=EXCLUDED.question, field_type=EXCLUDED.field_type, options=EXCLUDED.options, money_risk_rank=EXCLUDED.money_risk_rank, adds_trades=EXCLUDED.adds_trades, audience=EXCLUDED.audience, risk_note=EXCLUDED.risk_note, active=true;

-- ADDITION (9 fields)
INSERT INTO scope_checklists (tenant_id, project_type, field_key, question, field_type, options, money_risk_rank, adds_trades, audience, risk_note, active) VALUES
  (NULL, 'addition', 'purpose_size', 'What''s the addition for, and rough size?', 'choice', '["bedroom","bath_suite","family_room","kitchen_expansion","sunroom"]'::jsonb, 1, NULL, 'rep_client', 'Bath/kitchen purpose = full MEP scope inside the addition', true),
  (NULL, 'addition', 'foundation', 'Foundation type?', 'choice', '["crawl","slab","basement","pier"]'::jsonb, 2, ARRAY['Foundations - Poured']::text[], 'rep_client', 'Basement vs slab = 2-3× foundation cost; must reconcile with existing foundation depth', true),
  (NULL, 'addition', 'roof_tie_in', 'How does the new roof meet the old — extend ridge, perpendicular gable, shed, or second story?', 'choice', '["extend_ridge","perp_gable","shed","second_story"]'::jsonb, 3, ARRAY['Framing','Roofing']::text[], 'rep', 'Tie-in defines framing complexity; second story = whole different job (bearing walls, stairs)', true),
  (NULL, 'addition', 'hvac', 'Heat/cool the new space — extend existing, mini-split, or new unit?', 'choice', '["extend_existing","mini_split","new_system"]'::jsonb, 4, ARRAY['HVAC - Install']::text[], 'rep', 'Existing system rarely has capacity; "just extend it" = undersized everything', true),
  (NULL, 'addition', 'elec_panel', 'Panel capacity for a new room’s circuits? (photo)', 'choice', '["room_available","full","unknown"]'::jsonb, 5, ARRAY['Electrical - Service upgrade']::text[], 'rep', NULL, true),
  (NULL, 'addition', 'connection', 'How does it connect to the house — open passage, doorway, or hallway?', 'choice', '["open","door","hall"]'::jsonb, 6, ARRAY['Framing']::text[], 'rep_client', 'Open passage through exterior wall = header/beam + the wall is bearing', true),
  (NULL, 'addition', 'exterior_match', 'Match existing siding/roofing, or intentional contrast?', 'choice', '["match","contrast"]'::jsonb, 7, NULL, 'rep_client', 'Matching discontinued siding = whole-wall reside surprise', true),
  (NULL, 'addition', 'site', 'Setbacks, easements, slope, tree removal, utility lines in the footprint?', 'text', NULL, 8, NULL, 'rep', 'Setback violation = redesign; slope = stepped footings', true),
  (NULL, 'addition', 'interior_finish', 'Interior finish level — match house trim/doors/flooring, or new spec?', 'choice', '["match_existing","new_spec"]'::jsonb, 9, NULL, 'rep_client', NULL, true)
ON CONFLICT (tenant_id, project_type, field_key) DO UPDATE SET question=EXCLUDED.question, field_type=EXCLUDED.field_type, options=EXCLUDED.options, money_risk_rank=EXCLUDED.money_risk_rank, adds_trades=EXCLUDED.adds_trades, audience=EXCLUDED.audience, risk_note=EXCLUDED.risk_note, active=true;

-- ROOF (9 fields)
INSERT INTO scope_checklists (tenant_id, project_type, field_key, question, field_type, options, money_risk_rank, adds_trades, audience, risk_note, active) VALUES
  (NULL, 'roof', 'scope', 'Full replacement or repair?', 'choice', '["full_replace","repair_section"]'::jsonb, 1, ARRAY['Roofing']::text[], 'rep_client', NULL, true),
  (NULL, 'roof', 'layers', 'How many existing layers, and any known decking issues?', 'choice', '["one","two_plus","unknown"]'::jsonb, 2, ARRAY['Roofing']::text[], 'rep', '2+ layers = tearoff cost jump; soft decking = per-sheet replacement money', true),
  (NULL, 'roof', 'material', 'Material?', 'choice', '["asphalt","standing_seam","rpanel","shake"]'::jsonb, 3, ARRAY['Roofing']::text[], 'rep_client', NULL, true),
  (NULL, 'roof', 'shingle_grade', 'If asphalt — grade?', 'choice', '["3tab","architectural","designer"]'::jsonb, 4, ARRAY['Roofing']::text[], 'rep_client', NULL, true),
  (NULL, 'roof', 'pitch_access', 'Pitch and access — steep? Multi-story? Tight lot?', 'choice', '["walkable","steep","very_steep"]'::jsonb, 5, ARRAY['Roofing']::text[], 'rep', 'Steep/access = labor multiplier + safety setup', true),
  (NULL, 'roof', 'penetrations', 'Count/condition — chimneys, skylights, vents, satellite mounts?', 'text', NULL, 6, ARRAY['Roofing']::text[], 'rep', 'Chimney reflash, skylight replace-while-you''re-there, abandoned mounts — each a line item', true),
  (NULL, 'roof', 'ventilation', 'Ventilation plan?', 'choice', '["box","ridge_soffit","power"]'::jsonb, 7, ARRAY['Roofing']::text[], 'rep_client', 'Soffit intake blocked = warranty problem; upgrade to ridge = cut the deck', true),
  (NULL, 'roof', 'gutters', 'Gutters — keep, new 5", new 6", or add guards?', 'choice', '["keep","5k","6k","guards"]'::jsonb, 8, NULL, 'rep_client', NULL, true),
  (NULL, 'roof', 'insurance', 'Is this an insurance claim?', 'choice', '["cash","insurance_claim"]'::jsonb, 9, NULL, 'rep', 'Claim = supplement process, adjuster scope, different paper trail entirely', true)
ON CONFLICT (tenant_id, project_type, field_key) DO UPDATE SET question=EXCLUDED.question, field_type=EXCLUDED.field_type, options=EXCLUDED.options, money_risk_rank=EXCLUDED.money_risk_rank, adds_trades=EXCLUDED.adds_trades, audience=EXCLUDED.audience, risk_note=EXCLUDED.risk_note, active=true;

-- FENCE (9 fields)
INSERT INTO scope_checklists (tenant_id, project_type, field_key, question, field_type, options, money_risk_rank, adds_trades, audience, risk_note, active) VALUES
  (NULL, 'fence', 'length_layout', 'Rough linear feet and layout (photo/sketch of property lines)?', 'text', NULL, 1, NULL, 'rep_client', NULL, true),
  (NULL, 'fence', 'property_line', 'Property pins located, or building off assumption? Neighbor agreement?', 'choice', '["pins_located","survey_needed","assumed"]'::jsonb, 2, NULL, 'rep', 'Fence on the neighbor''s land = tearout. The #1 fence lawsuit', true),
  (NULL, 'fence', 'style', 'Style?', 'choice', '["privacy","shadowbox","board_on_board","picket","horizontal","split_rail","chain_link","aluminum"]'::jsonb, 3, NULL, 'rep_client', 'Horizontal = premium lumber grade + tighter posts', true),
  (NULL, 'fence', 'material', 'Material?', 'choice', '["pt","cedar","vinyl","composite"]'::jsonb, 4, NULL, 'rep_client', NULL, true),
  (NULL, 'fence', 'height', 'Height?', 'choice', '["4ft","6ft","8ft"]'::jsonb, 5, NULL, 'rep_client', '8ft = HOA/permit trigger in most KC metros + deeper posts', true),
  (NULL, 'fence', 'top_treatment', 'Top treatment?', 'choice', '["dogear","cap_trim","lattice"]'::jsonb, 6, NULL, 'rep_client', NULL, true),
  (NULL, 'fence', 'gates', 'Gates — how many walk, any double drive?', 'number', NULL, 7, NULL, 'rep_client', 'Gates are where fences fail; drive gate = posts in concrete sized up', true),
  (NULL, 'fence', 'terrain', 'Slope — rack, step, or flat? Rock/utilities where posts go?', 'choice', '["flat","rack","step"]'::jsonb, 8, ARRAY['Concrete - Footings']::text[], 'rep', 'Stepping = more material + labor; rock = auger time or core drilling', true),
  (NULL, 'fence', 'tearout', 'Existing fence tearout + haul?', 'choice', '["none","tearout_haul"]'::jsonb, 9, ARRAY['Demo']::text[], 'rep_client', NULL, true)
ON CONFLICT (tenant_id, project_type, field_key) DO UPDATE SET question=EXCLUDED.question, field_type=EXCLUDED.field_type, options=EXCLUDED.options, money_risk_rank=EXCLUDED.money_risk_rank, adds_trades=EXCLUDED.adds_trades, audience=EXCLUDED.audience, risk_note=EXCLUDED.risk_note, active=true;

-- BASEMENT (9 fields)
INSERT INTO scope_checklists (tenant_id, project_type, field_key, question, field_type, options, money_risk_rank, adds_trades, audience, risk_note, active) VALUES
  (NULL, 'basement', 'moisture', 'Any history of water — seepage, sump, efflorescence, musty smell? (photos of walls/floor)', 'choice', '["dry_confirmed","past_issues_resolved","active_unknown"]'::jsonb, 1, NULL, 'rep', 'Finishing a wet basement = doing it twice. THE basement fork — nothing proceeds until answered', true),
  (NULL, 'basement', 'egress', 'Will there be a bedroom? Existing egress window or new needed?', 'choice', '["no_bedroom","egress_exists","egress_new"]'::jsonb, 2, ARRAY['Concrete - Slabs']::text[], 'rep_client', 'New egress = concrete cut + well + drainage — $5-8k people never budget', true),
  (NULL, 'basement', 'bathroom', 'Bathroom — none, half, or full? Rough-in exist?', 'choice', '["none","half","full"]'::jsonb, 3, ARRAY['Plumbing - Rough-in']::text[], 'rep_client', 'No rough-in = breaking slab or sewage ejector pit', true),
  (NULL, 'basement', 'ceiling_height', 'Height under the lowest duct/beam, in inches?', 'number', NULL, 4, ARRAY['HVAC - Install']::text[], 'rep', '<7ft under obstructions = code problem or soffit maze; drives ceiling choice', true),
  (NULL, 'basement', 'ceiling', 'Ceiling treatment?', 'choice', '["drywall","drop","exposed_painted"]'::jsonb, 5, ARRAY['Drywall - Hang']::text[], 'rep_client', 'Drywall = lose access to everything above; drop = lose height', true),
  (NULL, 'basement', 'mechanicals', 'Furnace/WH/panel locations — staying open or getting a room? Clearances?', 'text', NULL, 6, ARRAY['HVAC - Install']::text[], 'rep', 'Code clearances + combustion air around mechanicals shape the whole layout', true),
  (NULL, 'basement', 'flooring', 'Floor?', 'choice', '["lvp","carpet","concrete_polished"]'::jsonb, 7, ARRAY['Flooring - LVP']::text[], 'rep_client', 'Any flooring over concrete = moisture test first (ties to moisture field)', true),
  (NULL, 'basement', 'bar', 'Bar — none, dry, wet, or kitchenette?', 'choice', '["none","dry","wet","kitchenette"]'::jsonb, 8, ARRAY['Plumbing - Rough-in','Electrical - Rough-in']::text[], 'rep_client', 'Wet = plumbing run; kitchenette = 20A circuits + venting question', true),
  (NULL, 'basement', 'elec_panel', 'Panel space for 4-8 new circuits? (photo)', 'choice', '["room_available","full","unknown"]'::jsonb, 9, ARRAY['Electrical - Service upgrade']::text[], 'rep', NULL, true)
ON CONFLICT (tenant_id, project_type, field_key) DO UPDATE SET question=EXCLUDED.question, field_type=EXCLUDED.field_type, options=EXCLUDED.options, money_risk_rank=EXCLUDED.money_risk_rank, adds_trades=EXCLUDED.adds_trades, audience=EXCLUDED.audience, risk_note=EXCLUDED.risk_note, active=true;

-- EXTERIOR (8 fields)
INSERT INTO scope_checklists (tenant_id, project_type, field_key, question, field_type, options, money_risk_rank, adds_trades, audience, risk_note, active) VALUES
  (NULL, 'exterior', 'scope', 'Whole house or sections?', 'choice', '["whole","sections"]'::jsonb, 1, NULL, 'rep_client', NULL, true),
  (NULL, 'exterior', 'existing_material', 'What''s on the house now, and year built?', 'text', NULL, 2, NULL, 'rep', 'Pre-''78 painted wood = lead protocol; old fiber siding = possible asbestos = abatement', true),
  (NULL, 'exterior', 'sheathing_condition', 'Known soft spots, woodpecker holes, or rot at corners/bottoms?', 'choice', '["unknown","known_spots","clean"]'::jsonb, 3, NULL, 'rep', 'Per-sheet sheathing replacement — set the allowance now or eat it later', true),
  (NULL, 'exterior', 'new_material', 'New siding?', 'choice', '["vinyl","fiber_cement","lp","board_batten","stone_accent"]'::jsonb, 4, NULL, 'rep_client', NULL, true),
  (NULL, 'exterior', 'profile', 'Profile?', 'choice', '["lap","dutch","vertical","shake_accent"]'::jsonb, 5, NULL, 'rep_client', NULL, true),
  (NULL, 'exterior', 'trim_wrap', 'Window/door trim — wrap aluminum, new composite trim, or keep?', 'choice', '["wrap","new_trim","keep"]'::jsonb, 6, NULL, 'rep_client', 'Trim is 20-30% of a siding job people don''t picture', true),
  (NULL, 'exterior', 'housewrap_insulation', 'Housewrap/foam layer under new siding?', 'choice', '["wrap_only","wrap_plus_foam","none_existing_ok"]'::jsonb, 7, ARRAY['Insulation']::text[], 'rep', NULL, true),
  (NULL, 'exterior', 'penetrations', 'Light fixtures, outlets, hose bibs, vents — reuse blocks or new mounts?', 'text', NULL, 8, NULL, 'rep', 'Every penetration = a block + flash detail', true)
ON CONFLICT (tenant_id, project_type, field_key) DO UPDATE SET question=EXCLUDED.question, field_type=EXCLUDED.field_type, options=EXCLUDED.options, money_risk_rank=EXCLUDED.money_risk_rank, adds_trades=EXCLUDED.adds_trades, audience=EXCLUDED.audience, risk_note=EXCLUDED.risk_note, active=true;

-- GUT (7 fields)
INSERT INTO scope_checklists (tenant_id, project_type, field_key, question, field_type, options, money_risk_rank, adds_trades, audience, risk_note, active) VALUES
  (NULL, 'gut', 'room_list', 'Which rooms/spaces are in scope? (list them all — each bath/kitchen/basement fires its own checklist)', 'text', NULL, 1, NULL, 'rep_client', NULL, true),
  (NULL, 'gut', 'systems_plumbing', 'Plumbing systems scope?', 'choice', '["replace","partial","reuse"]'::jsonb, 2, ARRAY['Plumbing - Rough-in']::text[], 'rep', 'The gut-job fork: cosmetic gut vs systems gut is a 2× total swing', true),
  (NULL, 'gut', 'systems_electrical', 'Electrical systems scope?', 'choice', '["replace","partial","reuse"]'::jsonb, 3, ARRAY['Electrical - Rough-in']::text[], 'rep', NULL, true),
  (NULL, 'gut', 'systems_hvac', 'HVAC systems scope?', 'choice', '["replace","partial","reuse"]'::jsonb, 4, ARRAY['HVAC - Install']::text[], 'rep', NULL, true),
  (NULL, 'gut', 'systems_panel', 'Electrical panel scope?', 'choice', '["replace","partial","reuse"]'::jsonb, 5, ARRAY['Electrical - Service upgrade']::text[], 'rep', NULL, true),
  (NULL, 'gut', 'occupied', 'Occupied during work, or vacant?', 'choice', '["vacant","occupied_phased"]'::jsonb, 6, NULL, 'rep', 'Occupied = phasing, dust protection, daily cleanup, timeline stretch', true),
  (NULL, 'gut', 'age_of_home', 'Year built?', 'choice', '["pre_1950","1950_1977","1978_2000","post_2000"]'::jsonb, 7, NULL, 'rep_client', NULL, true)
ON CONFLICT (tenant_id, project_type, field_key) DO UPDATE SET question=EXCLUDED.question, field_type=EXCLUDED.field_type, options=EXCLUDED.options, money_risk_rank=EXCLUDED.money_risk_rank, adds_trades=EXCLUDED.adds_trades, audience=EXCLUDED.audience, risk_note=EXCLUDED.risk_note, active=true;

-- Bathroom survivors (draft omits, owner kept): re-rank after the 18 draft fields; content preserved.
UPDATE scope_checklists SET money_risk_rank=19, audience='rep', active=true WHERE tenant_id IS NULL AND project_type='bathroom' AND field_key='shower_floor_tiled';
UPDATE scope_checklists SET money_risk_rank=20, audience='rep', active=true WHERE tenant_id IS NULL AND project_type='bathroom' AND field_key='drywall_wet_area';
UPDATE scope_checklists SET money_risk_rank=21, audience='rep', active=true WHERE tenant_id IS NULL AND project_type='bathroom' AND field_key='access_panel';
UPDATE scope_checklists SET money_risk_rank=22, audience='rep', active=true WHERE tenant_id IS NULL AND project_type='bathroom' AND field_key='shower_valve';
UPDATE scope_checklists SET money_risk_rank=23, audience='rep', active=true WHERE tenant_id IS NULL AND project_type='bathroom' AND field_key='shower_bench';

-- Modules: drop live keys superseded by draft renames; waterproofing (live, absent from draft) survives untouched.
DELETE FROM scope_modules WHERE tenant_id IS NULL AND module_key IN ('electrical_upgrade','water_mold_remediation');

INSERT INTO scope_modules (tenant_id, module_key, label, trigger_phrases, adds_fields, adds_trades, active) VALUES
  (NULL, 'structural', 'Framing / Structural Change', ARRAY['load bearing','remove wall','open concept','beam','vaulted','sagging','second story','curbless entry','covered deck roof','wall-hung toilet','foundation cut']::text[], '[{"field_key":"which_wall_or_span","question":"Which wall or span is affected?","field_type":"text"},{"field_key":"whats_above","question":"What''s above it? (photo)","field_type":"text"},{"field_key":"whats_inside_wall","question":"What''s inside the wall — ducts, plumbing, wiring?","field_type":"text"},{"field_key":"engineer_needed","question":"Engineer’s stamp needed?","field_type":"choice","options":["yes","no","unknown"]},{"field_key":"beam_exposure","question":"Beam exposure?","field_type":"choice","options":["flush","dropped"]}]'::jsonb, ARRAY['Framing','Demo','Drywall - Hang']::text[], true),
  (NULL, 'plumbing_relocation', 'Plumbing Fixture Relocation', ARRAY['fixture moves','wet island','new bath location','move the sink','basement bath no rough-in','move toilet','move shower','move tub']::text[], '[{"field_key":"distance_of_move","question":"How far is the fixture moving?","field_type":"text"},{"field_key":"drain_and_vent_path","question":"Drain + vent path available?","field_type":"text"},{"field_key":"floor_system","question":"Floor system?","field_type":"choice","options":["slab","joist","truss"]},{"field_key":"water_line_material","question":"Water line material?","field_type":"choice","options":["copper","pex","galv","unknown"]}]'::jsonb, ARRAY['Plumbing - Rough-in','Demo']::text[], true),
  (NULL, 'plumbing_age', 'Aging Plumbing / Repipe', ARRAY['pre-1978 home','galvanized','cast iron','low pressure','old pipes']::text[], '[{"field_key":"supply_material","question":"Supply line material?","field_type":"choice","options":["copper","galv","pex","unknown"]},{"field_key":"drain_material","question":"Drain material?","field_type":"choice","options":["pvc","cast","unknown"]},{"field_key":"water_heater_age","question":"Water heater age?","field_type":"text"},{"field_key":"main_shutoff_works","question":"Main shutoff works?","field_type":"choice","options":["yes","no","unknown"]}]'::jsonb, ARRAY['Plumbing - Service upgrade','Plumbing - Rough-in']::text[], true),
  (NULL, 'electrical_service', 'Electrical Service / Circuits', ARRAY['panel full','new circuits','induction','hot tub','ev charger','heated floor','kitchen remodel','addition','basement finish']::text[], '[{"field_key":"panel_photo","question":"Photo of the panel","field_type":"text"},{"field_key":"amperage","question":"Service amperage?","field_type":"choice","options":["100","150","200","unknown"]},{"field_key":"breaker_space","question":"Open breaker space?","field_type":"choice","options":["yes","no","unknown"]},{"field_key":"aluminum_wiring","question":"Aluminum wiring?","field_type":"choice","options":["yes","no","unknown"]},{"field_key":"knob_tube","question":"Knob & tube wiring?","field_type":"choice","options":["yes","no","unknown"]}]'::jsonb, ARRAY['Electrical - Service upgrade','Electrical - Rough-in']::text[], true),
  (NULL, 'gas_line', 'Gas Line', ARRAY['gas range','gas fireplace','gas grill line','fuel change','range relocation']::text[], '[{"field_key":"meter_location","question":"Gas meter location?","field_type":"text"},{"field_key":"existing_line_size","question":"Existing line size?","field_type":"text"},{"field_key":"run_distance","question":"Run distance to appliance?","field_type":"text"},{"field_key":"appliance_btu_total","question":"Total appliance BTU?","field_type":"text"}]'::jsonb, NULL, true),
  (NULL, 'hvac_mod', 'HVAC Modification', ARRAY['wall removal','soffit removal','addition','basement finish','duct reroute','no vent in that room']::text[], '[{"field_key":"whats_in_the_soffit_or_wall","question":"What''s in the soffit/wall? (photo)","field_type":"text"},{"field_key":"system_capacity_known","question":"System capacity known?","field_type":"choice","options":["yes","no","unknown"]},{"field_key":"duct_path_available","question":"Duct path available?","field_type":"choice","options":["yes","no","unknown"]},{"field_key":"returns_affected","question":"Returns affected?","field_type":"choice","options":["yes","no","unknown"]}]'::jsonb, ARRAY['HVAC - Install']::text[], true),
  (NULL, 'water_mold', 'Water / Mold Remediation', ARRAY['water damage','leak','mold','musty','flooded','stains in photos','basement moisture']::text[], '[{"field_key":"source_active_or_resolved","question":"Source active or resolved?","field_type":"choice","options":["active","resolved","unknown"]},{"field_key":"visible_extent","question":"Visible extent? (photos)","field_type":"text"},{"field_key":"materials_affected","question":"Materials affected?","field_type":"text"},{"field_key":"remediation_scope","question":"Remediation scope?","field_type":"choice","options":["surface","tearout","pro_remediation"]}]'::jsonb, ARRAY['Demo','Drywall - Hang']::text[], true),
  (NULL, 'rot_repair', 'Rot / Structural Repair', ARRAY['soft decking','ledger boards','siding bottoms','spongy','old deck reuse','roof decking condition']::text[], '[{"field_key":"probe_findings","question":"Probe findings? (photos)","field_type":"text"},{"field_key":"allowance_or_fixed","question":"Allowance or fixed price on the repair?","field_type":"choice","options":["allowance","fixed"]},{"field_key":"extent_unknown_flag","question":"Extent unknown?","field_type":"bool"}]'::jsonb, ARRAY['Framing','Demo']::text[], true),
  (NULL, 'window_door_change', 'Window / Door Change', ARRAY['new window','bigger opening','patio door','wet-wall window','addition connection']::text[], '[{"field_key":"opening_size_change","question":"Opening size change?","field_type":"choice","options":["same","bigger","smaller","new"]},{"field_key":"wall_type","question":"Wall type?","field_type":"choice","options":["bearing","non","unknown"]},{"field_key":"exterior_patch_material","question":"Exterior patch material?","field_type":"text"},{"field_key":"header_needed","question":"New header needed?","field_type":"choice","options":["yes","no","unknown"]}]'::jsonb, ARRAY['Framing']::text[], true),
  (NULL, 'exterior_tie_in', 'Exterior Envelope Tie-In', ARRAY['ledger attach','roof tie-in','new penetrations','hood vent','bath vent','addition','window changes']::text[], '[{"field_key":"siding_material_at_tie_in","question":"Siding material at the tie-in?","field_type":"text"},{"field_key":"flashing_detail","question":"Flashing detail?","field_type":"text"},{"field_key":"match_or_patch","question":"Match or patch?","field_type":"choice","options":["match","patch"]},{"field_key":"discontinued_material_risk","question":"Discontinued material risk?","field_type":"choice","options":["yes","no","unknown"]}]'::jsonb, NULL, true),
  (NULL, 'hazmat', 'Hazardous Materials (Lead / Asbestos)', ARRAY['pre-1978','popcorn ceiling','old tile','asbestos','old fiber siding','vermiculite']::text[], '[{"field_key":"year_built_confirmed","question":"Year built confirmed?","field_type":"text"},{"field_key":"suspect_materials","question":"Suspect materials? (photos)","field_type":"text"},{"field_key":"test_or_assume","question":"Test or assume?","field_type":"choice","options":["test","assume"]},{"field_key":"abatement_budget_flag","question":"Abatement budget flagged?","field_type":"bool"}]'::jsonb, ARRAY['Demo']::text[], true),
  (NULL, 'permit_code', 'Permit / Code', ARRAY['structural work','egress','deck over 30','8ft fence','additions','new bath','covered roof','property line']::text[], '[{"field_key":"jurisdiction","question":"Jurisdiction / AHJ?","field_type":"text"},{"field_key":"permit_by","question":"Permit pulled by?","field_type":"choice","options":["contractor","owner"]},{"field_key":"hoa","question":"HOA approval needed?","field_type":"choice","options":["yes","no","unknown"]},{"field_key":"survey_needed","question":"Survey needed?","field_type":"choice","options":["yes","no","unknown"]}]'::jsonb, NULL, true),
  (NULL, 'accessibility', 'Accessibility / Aging in Place', ARRAY['aging in place','wheelchair','grab bars','curbless','comfort-height','mom is moving in']::text[], '[{"field_key":"door_widths","question":"Door widths?","field_type":"text"},{"field_key":"grab_bar_blocking","question":"Grab-bar blocking now or future?","field_type":"choice","options":["now","future","none"]},{"field_key":"threshold_heights","question":"Threshold heights?","field_type":"text"},{"field_key":"future_proofing_level","question":"Future-proofing level?","field_type":"choice","options":["full","partial","none"]}]'::jsonb, NULL, true),
  (NULL, 'demolition', 'Demolition / Disposal', ARRAY['tearout','tearoff','haul away','existing structure removal']::text[], '[{"field_key":"dumpster_count_size","question":"Dumpster count/size?","field_type":"text"},{"field_key":"salvage_items","question":"Salvage items?","field_type":"text"},{"field_key":"utility_disconnects_needed","question":"Utility disconnects needed?","field_type":"choice","options":["yes","no","unknown"]},{"field_key":"haul_access","question":"Haul access?","field_type":"text"}]'::jsonb, ARRAY['Demo']::text[], true)
ON CONFLICT (tenant_id, module_key) DO UPDATE SET label=EXCLUDED.label, trigger_phrases=EXCLUDED.trigger_phrases, adds_fields=EXCLUDED.adds_fields, adds_trades=EXCLUDED.adds_trades, active=true;

-- Conflict + omission rules (§11 + answer-driven FIRES). Inert shape-proofs until Phase 3.
INSERT INTO scope_conflict_rules (tenant_id, rule_key, sources_compared, conflict_condition, question_when_conflict, active) VALUES
  (NULL, 'bath_config_photo_conflict', ARRAY['typed','photo']::text[], 'answer says tub but photo shows walk-in (or vice versa)', 'Which is the plan — keeping what’s there or changing the tub/shower config?', true),
  (NULL, 'bath_curbless_floor_unknown', ARRAY['answer']::text[], 'shower_entry=curbless AND floor system unknown', 'Curbless needs a recessed pan — is the joist direction/subfloor recess feasible? (fires structural)', true),
  (NULL, 'bath_tileheight_no_vent', ARRAY['answer']::text[], 'tile_height=ceiling AND ventilation unanswered', 'Tile to the ceiling adds moisture load — what’s the exhaust fan situation?', true),
  (NULL, 'bath_wetwall_window_omission', ARRAY['plan','typed']::text[], 'plan/photo shows a window in the wet wall AND wet_wall_window unanswered', 'The plan shows a window in the wet wall — staying as-is, moved, or closed in?', true),
  (NULL, 'bath_heatedfloor_panel_unknown', ARRAY['answer']::text[], 'heated_floor=yes AND electrical panel unknown', 'Heated floor needs a dedicated circuit — is there panel space? (fires electrical_service)', true),
  (NULL, 'bath_glass_omission', ARRAY['answer']::text[], 'tub/shower config answered but shower_glass unanswered', 'Glass is the biggest forgotten line item — frameless, framed, or curtain?', true),
  (NULL, 'kitch_wet_island_slab', ARRAY['answer']::text[], 'island=wet AND floor_system=slab', 'Wet island on a slab = cutting concrete — is that cost acknowledged?', true),
  (NULL, 'kitch_layout_keep_move_conflict', ARRAY['typed']::text[], 'layout=keep but client mentions moving the fridge/sink/range', 'That’s a reconfigure — re-confirm the layout answer.', true),
  (NULL, 'kitch_wall_removal_block', ARRAY['answer']::text[], 'wall_removal AND whats_inside_wall unanswered', 'What’s inside the wall coming out — ducts, plumbing, wiring? (photo or answer required)', true),
  (NULL, 'kitch_gas_to_induction_elec', ARRAY['answer']::text[], 'appliances change gas→induction AND electrical_service not fired', 'Induction needs 240V — fire the electrical service check.', true),
  (NULL, 'kitch_venting_omission', ARRAY['answer']::text[], 'any range change AND venting unanswered', 'Range change touches venting — type, and does it vent outside today?', true),
  (NULL, 'deck_height_railing', ARRAY['answer']::text[], 'size_height>30in AND railing none/unanswered', 'Over 30" requires guardrail by code — which railing?', true),
  (NULL, 'deck_composite_reuse_framing', ARRAY['answer']::text[], 'material=composite AND existing_deck=reuse_framing', 'Composite needs 16" OC or better — is the joist spacing confirmed? (photo)', true),
  (NULL, 'deck_roof_freestanding_conflict', ARRAY['answer']::text[], 'overhead=roof AND attachment=freestanding', 'A covered roof needs a house tie-in or a self-supporting structure — clarify.', true),
  (NULL, 'deck_footings_utilities_omission', ARRAY['answer']::text[], 'footings needed AND utilities_below unanswered', 'Where do the footings land — any utilities/septic/irrigation located?', true),
  (NULL, 'addn_bathsuite_plumbing', ARRAY['answer']::text[], 'purpose=bath_suite AND plumbing_relocation not fired', 'A bath suite = full plumbing scope — fire plumbing relocation.', true),
  (NULL, 'addn_foundation_depth', ARRAY['answer']::text[], 'foundation=basement AND existing house on slab/crawl', 'Is the foundation depth transition acknowledged? (cost flag)', true),
  (NULL, 'addn_second_story_structural', ARRAY['answer']::text[], 'roof_tie_in=second_story AND structural not fired', 'Second story = bearing walls + stairs — fire structural (always).', true),
  (NULL, 'addn_hvac_block', ARRAY['answer']::text[], 'hvac unanswered', 'How is the new space heated/cooled? (the #1 addition miss — required before scope-complete)', true),
  (NULL, 'roof_layers_tearoff_flag', ARRAY['answer']::text[], 'layers=two_plus AND estimate lacks a tearoff line', 'Two-plus layers — confirm the tearoff line is in the estimate.', true),
  (NULL, 'roof_material_change_decking', ARRAY['answer']::text[], 'material changes asphalt→metal AND decking condition unknown', 'Switching to metal — what’s the decking condition?', true),
  (NULL, 'roof_insurance_flag', ARRAY['answer']::text[], 'insurance_claim=yes', 'Insurance claim = supplement workflow + adjuster scope + different paper trail.', true),
  (NULL, 'fence_property_line_flag', ARRAY['answer']::text[], 'property_line=assumed', 'Property line assumed — hard flag on the proposal (liability language).', true),
  (NULL, 'fence_height_permit', ARRAY['answer']::text[], 'height=8ft AND permit_code not fired', '8ft fence = permit/HOA trigger — fire permit/code.', true),
  (NULL, 'fence_gates_omission', ARRAY['answer']::text[], 'gates unanswered', 'Every fence has at least one gate — how many walk / any drive gate?', true),
  (NULL, 'bsmt_moisture_block', ARRAY['answer']::text[], 'moisture=active_unknown', 'Active/unknown water — water_mold module is mandatory; nothing proceeds until resolved.', true),
  (NULL, 'bsmt_bath_roughin', ARRAY['answer']::text[], 'bathroom=full AND rough-in unanswered', 'Full bath — does a rough-in exist, or is it slab-cut vs ejector? ($5k+ fork)', true),
  (NULL, 'bsmt_egress_permit', ARRAY['answer']::text[], 'egress_new AND permit_code not fired', 'New egress = concrete cut + permit — fire permit/code.', true),
  (NULL, 'bsmt_ceiling_height_soffit', ARRAY['answer']::text[], 'ceiling_height<7ft under ducts AND ceiling=drywall', 'Low clearance under ducts with a drywall ceiling — soffit maze or duct reroute?', true),
  (NULL, 'ext_year_hazmat', ARRAY['answer']::text[], 'year_built<1978 AND hazmat not fired', 'Pre-1978 exterior = lead/asbestos protocol — fire hazmat (always).', true),
  (NULL, 'ext_sheathing_allowance', ARRAY['answer']::text[], 'sheathing_condition=unknown', 'Unknown sheathing — set the rot allowance conversation (allowance line on the proposal).', true),
  (NULL, 'univ_water_keyword_firewatermold', ARRAY['answer']::text[], 'any answer mentions water/mold/leak keywords AND water_mold not fired', 'Water/mold/leak mentioned — fire the water_mold module.', true),
  (NULL, 'univ_pre1978_hazmat', ARRAY['answer']::text[], 'age_of_home=pre_1978 anywhere', 'Pre-1978 home — hazmat fires, no exceptions.', true),
  (NULL, 'univ_client_supplied_flag', ARRAY['answer']::text[], 'client-supplied materials anywhere', 'Client-supplied materials — delivery/damage/spec responsibility language on the proposal.', true),
  (NULL, 'univ_residual_unknown', ARRAY['answer']::text[], 'something mentioned matches no field and no module', 'I don’t have a module for this — tell me more. (never silently dropped)', true)
ON CONFLICT (tenant_id, rule_key) DO UPDATE SET sources_compared=EXCLUDED.sources_compared, conflict_condition=EXCLUDED.conflict_condition, question_when_conflict=EXCLUDED.question_when_conflict, active=true;

COMMIT;
